using System.Text.Json;
using PiperPlus.Core.Inference;

namespace PiperPlus.Core.Tests;

/// <summary>
/// Cross-runtime short-text contract parity tests.
///
/// Loads <c>tests/fixtures/short_text/contract.json</c> (regenerated by
/// <c>scripts/regenerate_short_text_fixture.py</c> from
/// <c>docs/spec/short-text-contract.toml</c>) and asserts that the C#
/// implementation in <see cref="ShortTextProcessor"/> uses the same
/// canonical values that the other runtimes (Python, Rust, Go, C++,
/// WASM/JS) are expected to match.
///
/// Constants exposed as <c>internal const</c> are checked directly via
/// <c>InternalsVisibleTo</c>. Values that are not exposed as named
/// constants (currently <c>noise_scale_min_ratio</c> and
/// <c>noise_w_min_ratio</c>, hard-coded inside <c>AdjustScales</c>) are
/// verified behaviourally by invoking the public/internal API and
/// comparing the result against the expected formula.
/// </summary>
public sealed class ShortTextContractTests
{
    // ------------------------------------------------------------------
    // Fixture loader (cached across all facts in this class)
    // ------------------------------------------------------------------

    private static readonly JsonElement Contract = LoadContract();

    private static JsonElement LoadContract()
    {
        string path = Path.Combine(
            AppContext.BaseDirectory,
            "TestData",
            "short_text_contract.json");
        if (!File.Exists(path))
        {
            throw new FileNotFoundException(
                $"short_text_contract.json not found at {path}. " +
                "Run `python scripts/regenerate_short_text_fixture.py` and rebuild.");
        }
        using var stream = File.OpenRead(path);
        var doc = JsonDocument.Parse(stream);
        return doc.RootElement.Clone();
    }

    private static int GetInt(string section, string key)
        => Contract.GetProperty(section).GetProperty(key).GetInt32();

    private static float GetFloat(string section, string key)
        => Contract.GetProperty(section).GetProperty(key).GetSingle();

    private static string GetString(string section, string key)
        => Contract.GetProperty(section).GetProperty(key).GetString()!;

    private static bool GetBool(string section, string key)
        => Contract.GetProperty(section).GetProperty(key).GetBoolean();

    // ------------------------------------------------------------------
    // 1. Padding constants (named)
    // ------------------------------------------------------------------

    [Fact]
    public void Padding_MinPhonemeIds_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.MinPhonemeIds, GetInt("padding", "min_phoneme_ids"));
    }

    [Fact]
    public void Padding_MinBodyForStrategyA_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.MinBodyForStrategyA, GetInt("padding", "min_body_for_strategy_a"));
    }

    [Fact]
    public void Padding_PauseTokenId_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.PauseId, (long)GetInt("padding", "pause_token_id"));
    }

    [Fact]
    public void Padding_Split_FrontBackEven_BackGetsExtraOnOddDeficit()
    {
        // Spec [padding].split = "front_back_even":
        //   "Padding is split evenly: half inserted after BOS (index 0), half
        //    inserted before EOS (last index). When the total is odd, the back
        //    half gets the extra token."
        Assert.Equal("front_back_even", GetString("padding", "split"));

        // Body of length 4 + BOS + EOS = 6 phonemes; deficit = 15 - 6 = 9 (odd).
        // Expected: front = 4, back = 5 (back gets the extra token).
        long[] phonemeIds = [1L, 10L, 10L, 10L, 10L, 2L]; // BOS, 4×body, EOS
        var (paddedIds, _, frontPad, backPad) = ShortTextProcessor.PadPhonemeIds(phonemeIds, prosodyFlat: null);

        Assert.Equal(ShortTextProcessor.MinPhonemeIds, paddedIds.Length);
        Assert.Equal(9, frontPad + backPad);
        Assert.Equal(4, frontPad);
        Assert.Equal(5, backPad);
    }

    [Fact]
    public void Padding_Split_FrontBackEven_EvenSplitOnEvenDeficit()
    {
        // Body of length 5 + BOS + EOS = 7; deficit = 15 - 7 = 8 (even).
        // Expected: front = back = 4.
        long[] phonemeIds = [1L, 10L, 10L, 10L, 10L, 10L, 2L];
        var (_, _, frontPad, backPad) = ShortTextProcessor.PadPhonemeIds(phonemeIds, prosodyFlat: null);
        Assert.Equal(8, frontPad + backPad);
        Assert.Equal(frontPad, backPad);
    }

    [Fact]
    public void Padding_ProsodyFill_Zero()
    {
        // Spec [padding].prosody_fill = 0 — prosody features (when present)
        // are zero-filled at padding positions.
        Assert.Equal(0, GetInt("padding", "prosody_fill"));

        // 5-phoneme input → prosodyFlat length = 5 * 3 = 15.
        // Each phoneme has 3 prosody floats (a1, a2, a3). After padding to
        // MinPhonemeIds=15, the padded flat array has length 45 with the
        // pad positions zero-filled.
        long[] phonemeIds = [1L, 10L, 10L, 10L, 2L];
        long[] prosodyFlat =
        [
            11L, 12L, 13L,  // BOS (index 0)
            21L, 22L, 23L,  // body[0]
            31L, 32L, 33L,  // body[1]
            41L, 42L, 43L,  // body[2]
            51L, 52L, 53L,  // EOS
        ];

        var (paddedIds, paddedProsody, frontPad, backPad) = ShortTextProcessor.PadPhonemeIds(
            phonemeIds, prosodyFlat);

        Assert.NotNull(paddedProsody);
        Assert.Equal(paddedIds.Length * 3, paddedProsody!.Length);

        // Original BOS prosody (11,12,13) preserved at indices 0..2.
        Assert.Equal(11L, paddedProsody[0]);
        Assert.Equal(12L, paddedProsody[1]);
        Assert.Equal(13L, paddedProsody[2]);

        // The `frontPad` pad positions (3 floats each) directly after BOS
        // must all be zero — anchoring `prosody_fill = 0`.
        for (int padIndex = 0; padIndex < frontPad; padIndex++)
        {
            int baseOffset = (1 + padIndex) * 3;
            Assert.Equal(0L, paddedProsody[baseOffset]);
            Assert.Equal(0L, paddedProsody[baseOffset + 1]);
            Assert.Equal(0L, paddedProsody[baseOffset + 2]);
        }

        // The `backPad` pad positions immediately before EOS must also be zero.
        int eosIndex = paddedIds.Length - 1;
        for (int padIndex = 0; padIndex < backPad; padIndex++)
        {
            int baseOffset = (eosIndex - 1 - padIndex) * 3;
            Assert.Equal(0L, paddedProsody[baseOffset]);
            Assert.Equal(0L, paddedProsody[baseOffset + 1]);
            Assert.Equal(0L, paddedProsody[baseOffset + 2]);
        }
    }

    // ------------------------------------------------------------------
    // 2. Trim constants (named)
    // ------------------------------------------------------------------

    [Fact]
    public void Trim_ThresholdRms_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.TrimThresholdRms, GetFloat("trim", "threshold_rms"));
    }

    [Fact]
    public void Trim_MinSamples_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.TrimMinSamples, GetInt("trim", "min_samples"));
    }

    [Fact]
    public void Trim_WindowSize_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.TrimWindowSize, GetInt("trim", "window_size"));
    }

    [Fact]
    public void Trim_SampleRate_ContractReferenceValue()
    {
        // Reference value used to derive min_samples (= 0.1s × 22050).
        // No corresponding C# constant; this is a spec self-check.
        Assert.Equal(22050, GetInt("trim", "sample_rate"));
    }

    // ------------------------------------------------------------------
    // 3. Scales (behavioural — values are inlined inside AdjustScales)
    // ------------------------------------------------------------------

    [Fact]
    public void Scales_NoiseScaleMinRatio_MatchesContract()
    {
        // Formula: adjusted_noise_scale = noise_scale * max(noise_scale_min_ratio, ratio)
        // With phonemeIdCount = 0, ratio = 0, so adjusted = noiseScale * noise_scale_min_ratio.
        // For a baseline noiseScale of 1.0, adjusted equals noise_scale_min_ratio directly.
        float expectedRatio = GetFloat("scales", "noise_scale_min_ratio");
        var (adjustedNoiseScale, _) = ShortTextProcessor.AdjustScales(
            phonemeIdCount: 0,
            noiseScale: 1.0f,
            noiseW: 1.0f);

        Assert.Equal(expectedRatio, adjustedNoiseScale, precision: 5);
        // Pin the canonical contract value alongside the behavioural check.
        Assert.Equal(0.5f, expectedRatio);
    }

    [Fact]
    public void Scales_NoiseWMinRatio_MatchesContract()
    {
        float expectedRatio = GetFloat("scales", "noise_w_min_ratio");
        var (_, adjustedNoiseW) = ShortTextProcessor.AdjustScales(
            phonemeIdCount: 0,
            noiseScale: 1.0f,
            noiseW: 1.0f);

        Assert.Equal(expectedRatio, adjustedNoiseW, precision: 5);
        Assert.Equal(0.4f, expectedRatio);
    }

    [Fact]
    public void Scales_NoTreatmentForLongInputs()
    {
        // Sequences >= MinPhonemeIds must not be touched by AdjustScales.
        var (noiseScale, noiseW) = ShortTextProcessor.AdjustScales(
            phonemeIdCount: ShortTextProcessor.MinPhonemeIds + 5,
            noiseScale: 0.667f,
            noiseW: 0.8f);
        Assert.Equal(0.667f, noiseScale, precision: 5);
        Assert.Equal(0.8f, noiseW, precision: 5);
    }

    // ------------------------------------------------------------------
    // 4. SSML injection (named + behavioural)
    // ------------------------------------------------------------------

    [Fact]
    public void Ssml_ShortTextChars_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.ShortTextChars, GetInt("ssml_injection", "short_text_chars"));
    }

    [Fact]
    public void Ssml_SilencePadMs_MatchesContract()
    {
        Assert.Equal(ShortTextProcessor.SilencePadMs, GetInt("ssml_injection", "silence_pad_ms"));
    }

    [Fact]
    public void Ssml_SkipIfSsml_True()
    {
        // Spec [ssml_injection].skip_if_ssml = true:
        //   "Strategy C is skipped if the input already starts with '<speak>'."
        Assert.True(GetBool("ssml_injection", "skip_if_ssml"));

        // IsShortPlainText must return false for both lowercase and attributed
        // <speak> openers (the predicate that gates Strategy C).
        Assert.False(ShortTextProcessor.IsShortPlainText("<speak>hi</speak>"));
        Assert.False(ShortTextProcessor.IsShortPlainText("<speak version=\"1.0\">hi</speak>"));

        // A short non-SSML input still triggers Strategy C.
        Assert.True(ShortTextProcessor.IsShortPlainText("hi"));
    }

    [Fact]
    public void Ssml_BuildEmitsContractBreakDuration()
    {
        // WrapShortTextWithBreaks must emit <break time="{SilencePadMs}ms"/>
        // both before and after the escaped text — anchoring the canonical
        // silence_pad_ms = 300.
        string wrapped = ShortTextProcessor.WrapShortTextWithBreaks("hi");
        Assert.Contains($"<break time=\"{ShortTextProcessor.SilencePadMs}ms\"/>", wrapped);
        Assert.Contains("<speak>", wrapped);
        Assert.Contains("</speak>", wrapped);
    }
}
