package com.github.ayousanz.piper

import java.io.FileOutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder

/**
 * Audio data generated by Piper TTS.
 *
 * @param samples PCM audio samples (16-bit signed, mono)
 * @param sampleRate Sample rate in Hz (default: 22050)
 */
data class PiperAudio(
    val samples: ShortArray,
    val sampleRate: Int = 22050,
) {
    /** Duration of the audio in seconds. */
    val durationSeconds: Float
        get() = samples.size.toFloat() / sampleRate

    /** Save audio as a WAV file. */
    fun save(path: String) {
        FileOutputStream(path).use { fos ->
            val dataSize = samples.size * 2
            val header = ByteBuffer.allocate(44).order(ByteOrder.LITTLE_ENDIAN).apply {
                // RIFF header
                put("RIFF".toByteArray())
                putInt(dataSize + 36)
                put("WAVE".toByteArray())
                // fmt chunk
                put("fmt ".toByteArray())
                putInt(16) // PCM
                putShort(1) // PCM format
                putShort(1) // mono
                putInt(sampleRate)
                putInt(sampleRate * 2) // bytes per sec
                putShort(2) // block align
                putShort(16) // bits per sample
                // data chunk
                put("data".toByteArray())
                putInt(dataSize)
            }
            fos.write(header.array())

            val pcm = ByteBuffer.allocate(dataSize).order(ByteOrder.LITTLE_ENDIAN)
            samples.forEach { pcm.putShort(it) }
            fos.write(pcm.array())
        }
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is PiperAudio) return false
        return samples.contentEquals(other.samples) && sampleRate == other.sampleRate
    }

    override fun hashCode(): Int = 31 * samples.contentHashCode() + sampleRate
}
