// ZH-EN code-switching: loanword data loader + parse (TICKET-05 P1)

#include "chinese_loanword.hpp"

#include <array>
#include <cstdint>
#include <fstream>
#include <mutex>
#include <sstream>
#include <stdexcept>

#include "json.hpp"
#ifndef PIPER_PLUS_EMBEDDED_LOANWORD
#include "library_path.h"
#endif

namespace piper {

namespace {

// -------------------------------------------------------------------------
// Optional compile-time embedded JSON (mobile / Apple-embedded targets)
// -------------------------------------------------------------------------
#ifdef PIPER_PLUS_EMBEDDED_LOANWORD
#include "zh_en_loanword_data.h"  // CMake-generated by embed_json_as_header()
inline std::string load_embedded_json() {
    return std::string(reinterpret_cast<const char*>(zh_en_loanword_json),
                       zh_en_loanword_json_len);
}
#endif

// -------------------------------------------------------------------------
// JSON type helpers (for Python-equivalent error messages)
// -------------------------------------------------------------------------
const char* json_type_name(const nlohmann::json& v) {
    using T = nlohmann::json::value_t;
    switch (v.type()) {
    case T::null:           return "null";
    case T::boolean:        return "bool";
    case T::number_integer:
    case T::number_unsigned:
    case T::number_float:   return "number";
    case T::string:         return "string";
    case T::array:          return "list";
    case T::object:         return "dict";
    default:                return "unknown";
    }
}

void parse_section(const nlohmann::json& root,
                   const std::string& label,
                   const std::string& section,
                   std::unordered_map<std::string, std::vector<std::string>>& target) {
    auto it = root.find(section);
    if (it == root.end()) return;  // missing section ok (forward-compat)

    if (!it->is_object()) {
        std::ostringstream os;
        os << label << ": section '" << section << "' must be a mapping, got "
           << json_type_name(*it);
        throw LoanwordSchemaError(os.str());
    }

    for (auto sit = it->begin(); sit != it->end(); ++sit) {
        const auto& key = sit.key();
        const auto& val = sit.value();
        if (!val.is_array()) {
            std::ostringstream os;
            os << label << ": '" << section << "." << key
               << "' must be list[str], got " << val.dump();
            throw LoanwordSchemaError(os.str());
        }
        std::vector<std::string> items;
        items.reserve(val.size());
        for (const auto& elem : val) {
            if (!elem.is_string()) {
                std::ostringstream os;
                os << label << ": '" << section << "." << key
                   << "' must be list[str], got " << val.dump();
                throw LoanwordSchemaError(os.str());
            }
            items.push_back(elem.get<std::string>());
        }
        target.emplace(key, std::move(items));
    }
}

// -------------------------------------------------------------------------
// One-time default-data init (singleton)
// -------------------------------------------------------------------------
std::shared_ptr<const LoanwordData> g_default;
std::string g_default_error;
std::once_flag g_default_init_flag;

#ifndef PIPER_PLUS_EMBEDDED_LOANWORD
std::string get_default_loanword_path() {
    // Beside the executable, in the conventional dict_dir layout used by
    // the desktop installer (`<exe-dir>/data/zh_en_loanword.json`).
    std::array<char, 4096> buf{};
    if (piper_plus_get_exe_dir(buf.data(), static_cast<int>(buf.size())) == 0) {
        std::string dir(buf.data());
        return dir + "/data/zh_en_loanword.json";
    }
    return "data/zh_en_loanword.json";  // CWD-relative fallback
}
#endif

void init_default() {
    try {
#ifdef PIPER_PLUS_EMBEDDED_LOANWORD
        const std::string label = "zh_en_loanword.json (embedded)";
        const std::string json = load_embedded_json();
        auto data = parseLoanwordJson(label, json);
#else
        const std::string path = get_default_loanword_path();
        std::ifstream ifs(path);
        if (!ifs) {
            g_default_error = "failed to open " + path;
            return;
        }
        std::ostringstream buf;
        buf << ifs.rdbuf();
        auto data = parseLoanwordJson(path, buf.str());
#endif
        g_default = std::make_shared<const LoanwordData>(std::move(data));
    } catch (const std::exception& e) {
        g_default_error = e.what();
    }
}

}  // namespace

// =========================================================================
// Public API
// =========================================================================

LoanwordData parseLoanwordJson(const std::string& label, const std::string& json) {
    nlohmann::json root;
    try {
        root = nlohmann::json::parse(json);
    } catch (const nlohmann::json::parse_error& e) {
        throw LoanwordSchemaError(label + ": invalid JSON: " + e.what());
    }
    if (!root.is_object()) {
        throw LoanwordSchemaError(label + ": top-level must be a JSON object");
    }

    LoanwordData data;
    // Lenient version handling for forward-compat (review feedback C-1, R-C4).
    // Match Python / Rust / C# / Go loaders:
    //   1. Accept ``version`` if present and numeric.
    //   2. Fall back to ``schema_version`` if ``version`` is absent.
    //   3. Silently default to 1 if neither is present or the value is not a
    //      number.
    // Previously this loader required ``version`` to be a non-negative
    // integer, which made a future ``schema_version: 2`` manifest fail to
    // load in C++/Go even though Rust/Python/C# silently accepted it.
    data.version = 1;
    auto vit = root.find("version");
    if (vit != root.end() && vit->is_number_integer()) {
        data.version = vit->get<int>();
    } else {
        auto svit = root.find("schema_version");
        if (svit != root.end() && svit->is_number_integer()) {
            data.version = svit->get<int>();
        }
    }

    parse_section(root, label, "acronyms", data.acronyms);
    parse_section(root, label, "loanwords", data.loanwords);
    parse_section(root, label, "letter_fallback", data.letter_fallback);

    return data;
}

std::shared_ptr<const LoanwordData> getDefaultLoanwordData() {
    std::call_once(g_default_init_flag, init_default);
    return g_default;
}

const std::string& getDefaultLoanwordError() {
    std::call_once(g_default_init_flag, init_default);
    return g_default_error;
}

std::shared_ptr<const LoanwordData> loadLoanwordDataFromPath(const std::string& path) {
    std::ifstream ifs(path);
    if (!ifs) {
        throw std::runtime_error("loanword: failed to open " + path);
    }
    std::ostringstream buf;
    buf << ifs.rdbuf();
    auto data = parseLoanwordJson(path, buf.str());
    return std::make_shared<const LoanwordData>(std::move(data));
}

}  // namespace piper
