// Cross-runtime short-text contract conformance tests.
//
// Loads tests/fixtures/short_text/contract.json — generated by
// scripts/regenerate_short_text_fixture.py from
// docs/spec/short-text-contract.toml — and asserts that the Go runtime's
// constants and Strategy A/B/C behavior agree with the spec.
package piperplus

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

type contractFixture struct {
	SchemaVersion int `json:"schema_version"`
	Padding       struct {
		MinPhonemeIDs       int    `json:"min_phoneme_ids"`
		MinBodyForStrategyA int    `json:"min_body_for_strategy_a"`
		PauseTokenID        int    `json:"pause_token_id"`
		Split               string `json:"split"`
		ProsodyFill         int    `json:"prosody_fill"`
	} `json:"padding"`
	Trim struct {
		ThresholdRMS float64 `json:"threshold_rms"`
		MinSamples   int     `json:"min_samples"`
		WindowSize   int     `json:"window_size"`
		SampleRate   int     `json:"sample_rate"`
	} `json:"trim"`
	Scales struct {
		NoiseScaleMinRatio float64 `json:"noise_scale_min_ratio"`
		NoiseWMinRatio     float64 `json:"noise_w_min_ratio"`
	} `json:"scales"`
	SsmlInjection struct {
		ShortTextChars int  `json:"short_text_chars"`
		SilencePadMs   int  `json:"silence_pad_ms"`
		SkipIfSsml     bool `json:"skip_if_ssml"`
	} `json:"ssml_injection"`
}

func loadShortTextContract(t *testing.T) contractFixture {
	t.Helper()
	fixturePath := filepath.Join("..", "..", "..", "tests", "fixtures", "short_text", "contract.json")
	raw, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("failed to read contract.json at %s: %v", fixturePath, err)
	}
	var c contractFixture
	if err := json.Unmarshal(raw, &c); err != nil {
		t.Fatalf("failed to unmarshal contract.json: %v", err)
	}
	if c.SchemaVersion != 1 {
		t.Fatalf("unexpected schema_version: got %d, want 1", c.SchemaVersion)
	}
	return c
}

// TestShortTextContract_PaddingConstants verifies the Go padding-related
// constants match the canonical contract values.
func TestShortTextContract_PaddingConstants(t *testing.T) {
	c := loadShortTextContract(t)
	if minPhonemeIDs != c.Padding.MinPhonemeIDs {
		t.Errorf("minPhonemeIDs: got %d, want %d", minPhonemeIDs, c.Padding.MinPhonemeIDs)
	}
	if minBodyForStrategyA != c.Padding.MinBodyForStrategyA {
		t.Errorf("minBodyForStrategyA: got %d, want %d", minBodyForStrategyA, c.Padding.MinBodyForStrategyA)
	}
}

// TestShortTextContract_TrimConstants verifies the Go trim-related constants
// match the canonical contract values.
func TestShortTextContract_TrimConstants(t *testing.T) {
	c := loadShortTextContract(t)
	if math.Abs(trimThresholdRMS-c.Trim.ThresholdRMS) > 1e-9 {
		t.Errorf("trimThresholdRMS: got %g, want %g", trimThresholdRMS, c.Trim.ThresholdRMS)
	}
	if trimMinSamples != c.Trim.MinSamples {
		t.Errorf("trimMinSamples: got %d, want %d", trimMinSamples, c.Trim.MinSamples)
	}
	if trimWindowSize != c.Trim.WindowSize {
		t.Errorf("trimWindowSize: got %d, want %d", trimWindowSize, c.Trim.WindowSize)
	}
}

// TestShortTextContract_SsmlInjectionConstants verifies the Go SSML-injection
// (Strategy C) constants match the canonical contract values.
func TestShortTextContract_SsmlInjectionConstants(t *testing.T) {
	c := loadShortTextContract(t)
	if shortTextChars != c.SsmlInjection.ShortTextChars {
		t.Errorf("shortTextChars: got %d, want %d", shortTextChars, c.SsmlInjection.ShortTextChars)
	}
	if silencePadMs != c.SsmlInjection.SilencePadMs {
		t.Errorf("silencePadMs: got %d, want %d", silencePadMs, c.SsmlInjection.SilencePadMs)
	}
}

// TestShortTextContract_ScalesBehaviour verifies that adjustScalesForShortText
// implements noise_scale_min_ratio and noise_w_min_ratio. At phoneme length 0,
// ratio = 0 so the multiplier collapses to max(min_ratio, 0) = min_ratio.
func TestShortTextContract_ScalesBehaviour(t *testing.T) {
	c := loadShortTextContract(t)
	const baseScale float32 = 1.0
	const baseW float32 = 1.0
	gotScale, gotW := adjustScalesForShortText(0, baseScale, baseW)
	wantScale := float32(c.Scales.NoiseScaleMinRatio)
	wantW := float32(c.Scales.NoiseWMinRatio)
	if math.Abs(float64(gotScale-wantScale)) > 1e-6 {
		t.Errorf("noise_scale floor: got %g, want %g", gotScale, wantScale)
	}
	if math.Abs(float64(gotW-wantW)) > 1e-6 {
		t.Errorf("noise_w floor: got %g, want %g", gotW, wantW)
	}
}

// TestShortTextContract_PauseTokenAndSplit verifies padPhonemeIDs honors the
// contract's pause_token_id and front_back_even split policy.
func TestShortTextContract_PauseTokenAndSplit(t *testing.T) {
	c := loadShortTextContract(t)

	// 5 IDs (BOS=1, body=3 elements, EOS=2). Body length 3 == minBodyForStrategyA,
	// total 5 < minPhonemeIDs (15), so padding is applied.
	original := []int64{1, 10, 11, 12, 2}
	padded, didPad, frontPad, backPad := padPhonemeIDs(original)
	if !didPad {
		t.Fatalf("expected padding to be applied, got didPad=false")
	}
	if len(padded) != minPhonemeIDs {
		t.Fatalf("padded length: got %d, want %d", len(padded), minPhonemeIDs)
	}

	// Pause token assertion: every padded slot is contract.padding.pause_token_id.
	wantPause := int64(c.Padding.PauseTokenID)
	for i := 1; i < 1+frontPad; i++ {
		if padded[i] != wantPause {
			t.Errorf("front-pad[%d]: got %d, want %d (pause_token_id)", i, padded[i], wantPause)
		}
	}
	backStart := len(padded) - 1 - backPad
	for i := backStart; i < len(padded)-1; i++ {
		if padded[i] != wantPause {
			t.Errorf("back-pad[%d]: got %d, want %d (pause_token_id)", i, padded[i], wantPause)
		}
	}

	// Split policy: front_back_even — total even split, odd extra goes to back.
	if c.Padding.Split != "front_back_even" {
		t.Skipf("unsupported split mode in contract fixture: %q", c.Padding.Split)
	}
	totalPad := frontPad + backPad
	wantFront := totalPad / 2
	wantBack := totalPad - wantFront
	if frontPad != wantFront || backPad != wantBack {
		t.Errorf("split: got front=%d back=%d, want front=%d back=%d (front_back_even)",
			frontPad, backPad, wantFront, wantBack)
	}
}

// TestShortTextContract_ProsodyFill verifies prosody_fill=0 — padded prosody
// rows are zero-filled.
func TestShortTextContract_ProsodyFill(t *testing.T) {
	c := loadShortTextContract(t)
	if c.Padding.ProsodyFill != 0 {
		t.Skipf("contract.padding.prosody_fill is not 0: %d (test only validates the 0 case)", c.Padding.ProsodyFill)
	}

	original := [][3]int64{
		{1, 2, 3}, // BOS prosody
		{4, 5, 6}, // body prosody
		{7, 8, 9}, // EOS prosody
	}
	padded := padProsodyFeatures(original, 3, 7)
	if len(padded) != 7 {
		t.Fatalf("padded prosody length: got %d, want 7", len(padded))
	}

	// Layout: [BOS, 0, 0, body, 0, 0, EOS].
	zero := [3]int64{}
	checks := []struct {
		index int
		want  [3]int64
		label string
	}{
		{0, original[0], "BOS"},
		{1, zero, "front-pad-0"},
		{2, zero, "front-pad-1"},
		{3, original[1], "body"},
		{4, zero, "back-pad-0"},
		{5, zero, "back-pad-1"},
		{6, original[2], "EOS"},
	}
	for _, ch := range checks {
		if padded[ch.index] != ch.want {
			t.Errorf("padded[%d] (%s): got %v, want %v", ch.index, ch.label, padded[ch.index], ch.want)
		}
	}
}

// TestShortTextContract_SkipIfSsml verifies wrapShortTextWithBreaks does not
// flag SSML-prefixed text for silence padding.
func TestShortTextContract_SkipIfSsml(t *testing.T) {
	c := loadShortTextContract(t)
	if !c.SsmlInjection.SkipIfSsml {
		t.Skip("contract.ssml_injection.skip_if_ssml is false; skipping")
	}
	if _, shouldPad := wrapShortTextWithBreaks("<speak>あ</speak>"); shouldPad {
		t.Errorf("<speak> input must not trigger silence padding")
	}
	if _, shouldPad := wrapShortTextWithBreaks(`<speak version="1.0">あ</speak>`); shouldPad {
		t.Errorf("<speak ...> input must not trigger silence padding")
	}
}
