// Cross-runtime phoneme timing parity tests.
//
// Loads tests/fixtures/phoneme_timing/golden_matrix.json — generated by
// scripts/regenerate_timing_fixture.py from the canonical Python
// implementation in src/python_run/piper_plus/timing.py — and asserts that
// the Go DurationsToTiming output matches expected values for every case.
//
// Spec: docs/spec/phoneme-timing-contract.toml v1.0.
package piperplus

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

type goldenInputs struct {
	Durations     []float32 `json:"durations"`
	PhonemeTokens []string  `json:"phoneme_tokens"`
	SampleRate    int       `json:"sample_rate"`
	HopLength     int       `json:"hop_length"`
}

type goldenPhoneme struct {
	Phoneme    string  `json:"phoneme"`
	StartMs    float64 `json:"start_ms"`
	EndMs      float64 `json:"end_ms"`
	DurationMs float64 `json:"duration_ms"`
}

type goldenExpected struct {
	Phonemes        []goldenPhoneme `json:"phonemes"`
	TotalDurationMs float64         `json:"total_duration_ms"`
	TSV             string          `json:"tsv"`
	SRT             string          `json:"srt"`
	SampleRate      int             `json:"sample_rate"`
}

type goldenCase struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Inputs      goldenInputs   `json:"inputs"`
	Expected    goldenExpected `json:"expected"`
}

// goldenReverseMapCase covers the reverse map (issue #698). The cases above
// start from resolved token strings, so nothing in them says how
// phoneme_id_map is turned back into names. The contract said first-wins
// without defining "first", and the runtimes split three/three -- python /
// js / csharp iterated in insertion order, cpp / rust / go sorted. Every
// shipped model is collision-free, so all six agreed byte-for-byte and no
// test could see it.
type goldenReverseMapInputs struct {
	PhonemeIDMap map[string][]int64 `json:"phoneme_id_map"`
	PUANames     map[string]string  `json:"pua_names"`
}

type goldenReverseMapCase struct {
	Name        string                 `json:"name"`
	Description string                 `json:"description"`
	Inputs      goldenReverseMapInputs `json:"inputs"`
	// JSON object keys are strings; parsed back to int64 at comparison time.
	Expected map[string]string `json:"expected"`
}

type goldenMatrix struct {
	SchemaVersion   int                    `json:"schema_version"`
	Cases           []goldenCase           `json:"cases"`
	ReverseMapCases []goldenReverseMapCase `json:"reverse_map_cases"`
}

func loadGoldenMatrix(t *testing.T) goldenMatrix {
	t.Helper()
	// piperplus package cwd at test time -> ascend three levels to repo root.
	fixturePath := filepath.Join("..", "..", "..", "tests", "fixtures", "phoneme_timing", "golden_matrix.json")
	raw, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("failed to read golden_matrix at %s: %v", fixturePath, err)
	}
	var m goldenMatrix
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("failed to unmarshal golden_matrix: %v", err)
	}
	if m.SchemaVersion != 1 {
		t.Fatalf("unexpected schema_version: got %d, want 1", m.SchemaVersion)
	}
	if len(m.Cases) == 0 {
		t.Fatalf("golden matrix has no cases")
	}
	if len(m.ReverseMapCases) == 0 {
		t.Fatalf("golden matrix has no reverse_map_cases; regenerate with " +
			"scripts/regenerate_timing_fixture.py")
	}
	return m
}

// TestTimingParity_GoldenMatrix asserts byte-equivalent timing output across
// the canonical Python implementation and Go's DurationsToTiming, for every
// case in the cross-runtime golden fixture.
func TestTimingParity_GoldenMatrix(t *testing.T) {
	matrix := loadGoldenMatrix(t)

	// Tolerance: the canonical fixture stores values produced by Python's
	// float64 arithmetic; Go uses the same formula in float64. 1e-3 ms is
	// well below user-perceptible audio precision and accommodates any
	// IEEE-754 rounding differences along the cumulative sum.
	const eps = 1e-3

	for _, c := range matrix.Cases {
		t.Run(c.Name, func(t *testing.T) {
			got, err := DurationsToTiming(
				c.Inputs.Durations,
				c.Inputs.PhonemeTokens,
				c.Inputs.SampleRate,
				c.Inputs.HopLength,
			)
			if err != nil {
				t.Fatalf("DurationsToTiming returned error: %v", err)
			}

			if got.SampleRate != c.Expected.SampleRate {
				t.Errorf("sample_rate: got %d, want %d", got.SampleRate, c.Expected.SampleRate)
			}
			if math.Abs(got.TotalDurationMs-c.Expected.TotalDurationMs) > eps {
				t.Errorf("total_duration_ms: got %g, want %g", got.TotalDurationMs, c.Expected.TotalDurationMs)
			}

			// Formatted-output parity, byte for byte. The fixture held only
			// float milliseconds until spec_version 1.2, so the FORMATTING
			// layer went unchecked in every runtime -- rounding at .5 (#681),
			// CRLF on Windows (#683) and a thousands separator in the cue
			// index (#684) were each found by reading code, not by a test.
			if gotTSV := got.ToTSV(); gotTSV != c.Expected.TSV {
				t.Errorf("TSV bytes differ from the fixture:\ngot  %q\nwant %q", gotTSV, c.Expected.TSV)
			}
			if gotSRT := got.ToSRT(); gotSRT != c.Expected.SRT {
				t.Errorf("SRT bytes differ from the fixture:\ngot  %q\nwant %q", gotSRT, c.Expected.SRT)
			}
			if len(got.Phonemes) != len(c.Expected.Phonemes) {
				t.Fatalf("phonemes length: got %d, want %d", len(got.Phonemes), len(c.Expected.Phonemes))
			}
			for i, exp := range c.Expected.Phonemes {
				p := got.Phonemes[i]
				if p.Phoneme != exp.Phoneme {
					t.Errorf("phonemes[%d].phoneme: got %q, want %q", i, p.Phoneme, exp.Phoneme)
				}
				if math.Abs(p.StartMs-exp.StartMs) > eps {
					t.Errorf("phonemes[%d].start_ms: got %g, want %g", i, p.StartMs, exp.StartMs)
				}
				if math.Abs(p.EndMs-exp.EndMs) > eps {
					t.Errorf("phonemes[%d].end_ms: got %g, want %g", i, p.EndMs, exp.EndMs)
				}
				if math.Abs(p.DurationMs-exp.DurationMs) > eps {
					t.Errorf("phonemes[%d].duration_ms: got %g, want %g", i, p.DurationMs, exp.DurationMs)
				}
			}
		})
	}
}

// TestReverseMapParity_GoldenMatrix asserts the reverse map agrees with the
// canonical Python implementation, including which key wins an id collision.
func TestReverseMapParity_GoldenMatrix(t *testing.T) {
	m := loadGoldenMatrix(t)

	for _, c := range m.ReverseMapCases {
		t.Run(c.Name, func(t *testing.T) {
			got := BuildPhonemeIDReverseMap(c.Inputs.PhonemeIDMap, c.Inputs.PUANames)
			if len(got) != len(c.Expected) {
				t.Fatalf("entry count: got %d, want %d (%v vs %v)",
					len(got), len(c.Expected), got, c.Expected)
			}
			for key, want := range c.Expected {
				id, err := strconv.ParseInt(key, 10, 64)
				if err != nil {
					t.Fatalf("expected key %q is not an integer: %v", key, err)
				}
				if got[id] != want {
					t.Errorf("id %d: got %q, want %q", id, got[id], want)
				}
			}
		})
	}
}

// TestReverseMapParity_MirroredCollisionExists is anti-vacuity: without a
// MIRRORED colliding case, key order is unobservable. A collision-free map
// resolves identically under any iteration order, and a single colliding map
// can be satisfied by a runtime that happens to receive its keys already
// sorted.
//
// Go's json.Unmarshal into a map loses the JSON key order, so the pair is
// identified by the same key SET appearing in two cases rather than by the
// orders themselves -- the generator (scripts/regenerate_timing_fixture.py)
// is what asserts the two spellings differ.
func TestReverseMapParity_MirroredCollisionExists(t *testing.T) {
	m := loadGoldenMatrix(t)
	countByKeySet := map[string]int{}

	for _, c := range m.ReverseMapCases {
		seen := map[int64]bool{}
		collides := false
		for _, ids := range c.Inputs.PhonemeIDMap {
			for _, id := range ids {
				if seen[id] {
					collides = true
				}
				seen[id] = true
			}
		}
		if !collides {
			continue
		}
		keys := make([]string, 0, len(c.Inputs.PhonemeIDMap))
		for k := range c.Inputs.PhonemeIDMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		countByKeySet[strings.Join(keys, "\x00")]++
	}

	for _, n := range countByKeySet {
		if n >= 2 {
			return
		}
	}
	t.Fatalf("no colliding key set appears twice in the fixture, so these " +
		"cases cannot detect a runtime that iterates phoneme_id_map in " +
		"insertion order")
}
