// Cross-runtime phoneme timing parity tests.
//
// Loads tests/fixtures/phoneme_timing/golden_matrix.json — generated by
// scripts/regenerate_timing_fixture.py from the canonical Python
// implementation in src/python_run/piper/timing.py — and asserts that
// the Go DurationsToTiming output matches expected values for every case.
//
// Spec: docs/spec/phoneme-timing-contract.toml v1.0.
package piperplus

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"testing"
)

type goldenInputs struct {
	Durations     []float32 `json:"durations"`
	PhonemeTokens []string  `json:"phoneme_tokens"`
	SampleRate    int       `json:"sample_rate"`
	HopLength     int       `json:"hop_length"`
}

type goldenPhoneme struct {
	Phoneme    string  `json:"phoneme"`
	StartMs    float64 `json:"start_ms"`
	EndMs      float64 `json:"end_ms"`
	DurationMs float64 `json:"duration_ms"`
}

type goldenExpected struct {
	Phonemes        []goldenPhoneme `json:"phonemes"`
	TotalDurationMs float64         `json:"total_duration_ms"`
	SampleRate      int             `json:"sample_rate"`
}

type goldenCase struct {
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Inputs      goldenInputs   `json:"inputs"`
	Expected    goldenExpected `json:"expected"`
}

type goldenMatrix struct {
	SchemaVersion int          `json:"schema_version"`
	Cases         []goldenCase `json:"cases"`
}

func loadGoldenMatrix(t *testing.T) goldenMatrix {
	t.Helper()
	// piperplus package cwd at test time -> ascend three levels to repo root.
	fixturePath := filepath.Join("..", "..", "..", "tests", "fixtures", "phoneme_timing", "golden_matrix.json")
	raw, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("failed to read golden_matrix at %s: %v", fixturePath, err)
	}
	var m goldenMatrix
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("failed to unmarshal golden_matrix: %v", err)
	}
	if m.SchemaVersion != 1 {
		t.Fatalf("unexpected schema_version: got %d, want 1", m.SchemaVersion)
	}
	if len(m.Cases) == 0 {
		t.Fatalf("golden matrix has no cases")
	}
	return m
}

// TestTimingParity_GoldenMatrix asserts byte-equivalent timing output across
// the canonical Python implementation and Go's DurationsToTiming, for every
// case in the cross-runtime golden fixture.
func TestTimingParity_GoldenMatrix(t *testing.T) {
	matrix := loadGoldenMatrix(t)

	// Tolerance: the canonical fixture stores values produced by Python's
	// float64 arithmetic; Go uses the same formula in float64. 1e-3 ms is
	// well below user-perceptible audio precision and accommodates any
	// IEEE-754 rounding differences along the cumulative sum.
	const eps = 1e-3

	for _, c := range matrix.Cases {
		t.Run(c.Name, func(t *testing.T) {
			got, err := DurationsToTiming(
				c.Inputs.Durations,
				c.Inputs.PhonemeTokens,
				c.Inputs.SampleRate,
				c.Inputs.HopLength,
			)
			if err != nil {
				t.Fatalf("DurationsToTiming returned error: %v", err)
			}

			if got.SampleRate != c.Expected.SampleRate {
				t.Errorf("sample_rate: got %d, want %d", got.SampleRate, c.Expected.SampleRate)
			}
			if math.Abs(got.TotalDurationMs-c.Expected.TotalDurationMs) > eps {
				t.Errorf("total_duration_ms: got %g, want %g", got.TotalDurationMs, c.Expected.TotalDurationMs)
			}
			if len(got.Phonemes) != len(c.Expected.Phonemes) {
				t.Fatalf("phonemes length: got %d, want %d", len(got.Phonemes), len(c.Expected.Phonemes))
			}
			for i, exp := range c.Expected.Phonemes {
				p := got.Phonemes[i]
				if p.Phoneme != exp.Phoneme {
					t.Errorf("phonemes[%d].phoneme: got %q, want %q", i, p.Phoneme, exp.Phoneme)
				}
				if math.Abs(p.StartMs-exp.StartMs) > eps {
					t.Errorf("phonemes[%d].start_ms: got %g, want %g", i, p.StartMs, exp.StartMs)
				}
				if math.Abs(p.EndMs-exp.EndMs) > eps {
					t.Errorf("phonemes[%d].end_ms: got %g, want %g", i, p.EndMs, exp.EndMs)
				}
				if math.Abs(p.DurationMs-exp.DurationMs) > eps {
					t.Errorf("phonemes[%d].duration_ms: got %g, want %g", i, p.DurationMs, exp.DurationMs)
				}
			}
		})
	}
}
