#!/usr/bin/env python3
"""docs/spec ↔ src/ implementation の逆引きマップ生成 (Wave 3).

各 spec TOML が「どの実装 file を canonical 視しているか」 を text scan で
抽出し、 docs/spec/_implementation-map.auto.toml に dump する。

逆引き機能: file 名 → そのファイルを参照している spec list。 これにより
src/foo.py を編集したときに「foo.py を canonical 視している spec は何か」
を逆引きできる。

text scan の対象パターン:
  - "src/python/...", "src/rust/...", "src/cpp/...", "src/go/...",
    "src/csharp/...", "src/wasm/...", "android/...", "Sources/...",
    "tests/...", "tools/...", ".github/workflows/...", "scripts/..."

抽出した path はファイル中に literal で書かれているもののみ。 動的 glob
(`*`/`?`/`**`) はそのまま記録 (informative)。

このスクリプトは informative dump で enforce には使わない。 spec 編集時の
「影響範囲確認」 用 reference として利用。

Usage:
  uv run python scripts/build_spec_implementation_map.py
  # 出力: docs/spec/_implementation-map.auto.toml (generated)
"""

from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SPEC_DIR = REPO_ROOT / "docs" / "spec"
OUT_PATH = SPEC_DIR / "_implementation-map.auto.toml"

# Path literal regex — accepts repo-relative paths in TOML string contexts.
PATH_RE = re.compile(
    r"""
    [\"`']                              # opening quote
    (
      (?:src|tests|tools|scripts|docker|cmake|android|Sources|examples)/
      [a-zA-Z0-9_./\-]+
      |
      \.github/workflows/[a-zA-Z0-9_./\-]+\.ya?ml
      |
      Package\.swift
    )
    [\"`']                              # closing quote
    """,
    re.VERBOSE,
)


def extract_paths(text: str) -> set[str]:
    """Return the set of repo-relative path literals quoted inside `text`."""
    return {m.group(1) for m in PATH_RE.finditer(text)}


def main() -> int:
    if not SPEC_DIR.is_dir():
        print(f"error: {SPEC_DIR} not found", file=sys.stderr)
        return 1

    tomls = sorted(SPEC_DIR.glob("*.toml"))
    # Skip auto-generated file itself
    tomls = [p for p in tomls if p.name != "_implementation-map.auto.toml"]

    # spec_name -> sorted(paths)
    spec_to_paths: dict[str, list[str]] = {}
    # path -> [specs]
    path_to_specs: dict[str, list[str]] = defaultdict(list)

    for path in tomls:
        spec_name = path.name
        text = path.read_text(encoding="utf-8")
        paths = sorted(extract_paths(text))
        spec_to_paths[spec_name] = paths
        for p in paths:
            path_to_specs[p].append(spec_name)

    # Write out
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8") as f:
        f.write(
            "# AUTO-GENERATED — do not edit by hand.\n"
            "# Generated by scripts/build_spec_implementation_map.py\n"
            "# Reflects path literals quoted inside docs/spec/*.toml.\n"
            "\n"
            "[meta]\n"
            'generator = "scripts/build_spec_implementation_map.py"\n'
            'forward_compat_policy = "accept_unknown_fields"\n'
            "spec_count = " + str(len(spec_to_paths)) + "\n"
            "unique_paths = " + str(len(path_to_specs)) + "\n"
            "\n"
        )
        f.write("# Forward index: spec → paths\n")
        for spec_name, paths in sorted(spec_to_paths.items()):
            f.write(f'\n[spec."{spec_name}"]\n')
            if paths:
                f.write("paths = [\n")
                for p in paths:
                    f.write(f'    "{p}",\n')
                f.write("]\n")
            else:
                f.write("paths = []\n")

        f.write("\n# Reverse index: path → specs that mention it\n")
        for p in sorted(path_to_specs.keys()):
            specs = sorted(set(path_to_specs[p]))
            f.write(f'\n[path."{p}"]\n')
            f.write("specs = [\n")
            for s in specs:
                f.write(f'    "{s}",\n')
            f.write("]\n")

    print(
        f"Generated {OUT_PATH.relative_to(REPO_ROOT)}: "
        f"{len(spec_to_paths)} specs, {len(path_to_specs)} unique paths"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
