#!/usr/bin/env python3
"""Lockfile consistency gate (Wave 3).

Verifies that every supported runtime has a committed lockfile so that
transitive dependencies are reproducibly pinned across CI hosts and dev
workstations.

Scope:
  - Python (uv):       uv.lock at repo root
  - Rust (cargo):      src/rust/Cargo.lock
  - Go (modules):      src/go/go.sum, src/go/phonemize/go.sum
  - npm (g2p):         src/wasm/g2p/package-lock.json
  - npm (openjtalk):   src/wasm/openjtalk-web/package-lock.json
  - C# (NuGet):        src/csharp/PiperPlus.*/packages.lock.json (best-effort,
                        emitted lazily by CI on first restore)
  - Android (Gradle):  android/piper-plus*/gradle.lockfile (committed once
                        emitted; missing lockfile is a warning until L4 wires
                        ./gradlew --write-locks into release-kotlin-g2p.yml)
  - Swift (SPM):       Package.resolved (SPM auto-generates downstream;
                        repository copy is best-effort)

Fails (exit 1) when a hard-required lockfile is absent or zero-byte.
Warns (exit 0) when a soft-required lockfile (C# / Android / Swift) is
missing — those are emitted on first build and might not exist yet.

Run:
  uv run python scripts/check_lockfile_consistency.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# (relative_path, runtime_label, hard_required)
# Note: src/wasm/g2p/ は意図的に package-lock.json を gitignore している
# (.gitignore で "regenerated by `npm install`" 方針)。 一方
# openjtalk-web は WASM ビルドの reproducibility のため committed。
# 両者の policy 差を尊重し、 g2p は本 gate のスコープ外。
LOCKFILES: list[tuple[str, str, bool]] = [
    ("uv.lock", "Python (uv)", True),
    ("src/rust/Cargo.lock", "Rust (cargo)", True),
    ("src/go/go.sum", "Go (modules)", True),
    ("src/go/phonemize/go.sum", "Go phonemize (modules)", True),
    ("src/wasm/openjtalk-web/package-lock.json", "npm (openjtalk-web)", True),
    # NuGet packages.lock.json is emitted lazily by `dotnet restore` once
    # RestorePackagesWithLockFile=true takes effect. Until CI commits the
    # first batch we keep this as a warning.
    ("src/csharp/PiperPlus.Core/packages.lock.json", "C# Core (NuGet)", False),
    ("src/csharp/PiperPlus.Cli/packages.lock.json", "C# Cli (NuGet)", False),
    # Gradle dependency-locking enabled in android/build.gradle.kts (Wave 3).
    # Lockfiles will be emitted by `./gradlew :module:dependencies --write-locks`.
    ("android/piper-plus/gradle.lockfile", "Android piper-plus", False),
    ("android/piper-plus-g2p/gradle.lockfile", "Android piper-plus-g2p", False),
]


def check() -> int:
    missing_hard: list[str] = []
    missing_soft: list[str] = []
    empty: list[str] = []

    for rel, label, hard in LOCKFILES:
        path = REPO_ROOT / rel
        if not path.exists():
            (missing_hard if hard else missing_soft).append(f"{label}: {rel}")
            continue
        if path.stat().st_size == 0:
            empty.append(f"{label}: {rel}")

    if missing_hard or empty:
        print("ERROR: lockfile gate failed", file=sys.stderr)
        for entry in missing_hard:
            print(f"  missing (required): {entry}", file=sys.stderr)
        for entry in empty:
            print(f"  empty (required):   {entry}", file=sys.stderr)
        if missing_soft:
            print("  (soft-required lockfiles also missing — see warnings below)",
                  file=sys.stderr)
            for entry in missing_soft:
                print(f"    soft-missing: {entry}", file=sys.stderr)
        return 1

    if missing_soft:
        print("warning: optional lockfiles not yet committed:")
        for entry in missing_soft:
            print(f"  soft-missing: {entry}")
        print("  Run `dotnet restore` / `./gradlew :<module>:dependencies "
              "--write-locks` and commit the generated lockfile.")

    print(f"OK: {len(LOCKFILES) - len(missing_soft)} lockfile(s) present, "
          f"{len(missing_soft)} soft-missing.")
    return 0


if __name__ == "__main__":
    sys.exit(check())
