#!/usr/bin/env python3
"""Sanitize CLI --help output for canonical commit (T-003).

Each runtime's ``<binary> --help`` includes build- or run-time noise
(version strings, runner workspace paths, ANSI escapes). Committing the
raw output would produce drift on every release and on every CI runner.
This script strips that noise by applying the rules in
``scripts/sanitize_cli_help_rules.toml``, then prepends a fixed-format
header so the artifact is human-inspectable.

The output is plain text. The header has exactly four lines:

    # Auto-generated by .github/workflows/cli-help-extract.yml at <ISO8601>
    # Source: <command>
    # Runtime: <runtime>
    # Version: <piper-plus version>

Usage:
    python scripts/sanitize_cli_help.py \\
        --runtime python \\
        --source 'python -m piper --help' \\
        --in /tmp/piper-raw.txt \\
        --out docs/reference/cli-help/python.txt
"""

from __future__ import annotations

import argparse
import re
import sys
import tomllib
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from platform_utils import force_utf8_output


force_utf8_output()

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_RULES = REPO_ROOT / "scripts" / "sanitize_cli_help_rules.toml"
HEADER_TIMESTAMP_PLACEHOLDER = "<TIMESTAMP_PLACEHOLDER>"

SUPPORTED_RUNTIMES = (
    "python",
    "g2p-py",
    "rust",
    "csharp",
    "go",
    "wasm",
    "cpp",
)


def load_rules(rules_path: Path) -> list[dict[str, str]]:
    """Load and validate sanitization rules from a TOML file."""
    data = tomllib.loads(rules_path.read_text(encoding="utf-8"))
    rules = data.get("rules", [])
    if not isinstance(rules, list) or not rules:
        raise ValueError(
            f"{rules_path} has no [[rules]] entries. At least the "
            "generic timestamp rule is required.",
        )
    for i, rule in enumerate(rules):
        for key in ("runtime", "pattern", "replace_with"):
            if key not in rule:
                raise ValueError(
                    f"{rules_path} rule #{i} missing required key {key!r}.",
                )
    return rules


def apply_rules(
    text: str,
    runtime: str,
    rules: list[dict[str, Any]],
) -> str:
    """Apply every rule whose ``runtime`` matches (``*`` or exact match)."""
    result = text
    for rule in rules:
        if rule["runtime"] not in ("*", runtime):
            continue
        try:
            result = re.sub(
                rule["pattern"],
                rule["replace_with"],
                result,
                flags=re.MULTILINE,
            )
        except re.error as e:
            raise ValueError(
                f"Rule pattern {rule['pattern']!r} failed to compile: {e}",
            ) from e
    return result


def build_header(
    *,
    runtime: str,
    source: str,
    version: str,
    timestamp: str | None = None,
) -> str:
    """Build the 4-line header that prefixes every sanitized output."""
    ts = timestamp or datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# Auto-generated by .github/workflows/cli-help-extract.yml at {ts}\n"
        f"# Source: {source}\n"
        f"# Runtime: {runtime}\n"
        f"# Version: {version}\n"
    )


def sanitize(
    *,
    raw: str,
    runtime: str,
    source: str,
    version: str,
    rules: list[dict[str, Any]],
    timestamp: str | None = None,
) -> str:
    """Top-level entry: prepend header, apply rules to the body."""
    if runtime not in SUPPORTED_RUNTIMES:
        raise ValueError(
            f"Unsupported runtime {runtime!r}; expected one of {SUPPORTED_RUNTIMES}.",
        )
    header = build_header(
        runtime=runtime,
        source=source,
        version=version,
        timestamp=timestamp,
    )
    sanitized_body = apply_rules(raw, runtime, rules)
    if not sanitized_body.endswith("\n"):
        sanitized_body += "\n"
    return header + sanitized_body


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Sanitize CLI --help output for canonical commit.",
    )
    p.add_argument("--runtime", required=True, choices=SUPPORTED_RUNTIMES)
    p.add_argument(
        "--source", required=True, help="Invocation string written into the header."
    )
    p.add_argument(
        "--version", required=True, help="Version string written into the header."
    )
    p.add_argument(
        "--in",
        dest="input_path",
        required=True,
        type=Path,
        help="Path to the raw --help capture.",
    )
    p.add_argument(
        "--out",
        dest="output_path",
        required=True,
        type=Path,
        help="Path to write the sanitized output.",
    )
    p.add_argument(
        "--rules",
        type=Path,
        default=DEFAULT_RULES,
        help="Sanitization rules TOML (default: scripts/sanitize_cli_help_rules.toml).",
    )
    p.add_argument(
        "--timestamp",
        default=None,
        help="Override timestamp in header (for reproducible tests).",
    )
    args = p.parse_args(argv)

    if not args.input_path.exists():
        print(f"ERROR: {args.input_path} not found", file=sys.stderr)
        return 1
    if not args.rules.exists():
        print(f"ERROR: {args.rules} not found", file=sys.stderr)
        return 1

    raw = args.input_path.read_text(encoding="utf-8")
    rules = load_rules(args.rules)
    sanitized = sanitize(
        raw=raw,
        runtime=args.runtime,
        source=args.source,
        version=args.version,
        rules=rules,
        timestamp=args.timestamp,
    )
    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    args.output_path.write_text(sanitized, encoding="utf-8")
    print(
        f"Wrote sanitized output to {args.output_path} "
        f"({len(sanitized.splitlines())} lines)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
