// Cross-runtime phoneme timing parity test.
//
// Loads tests/fixtures/phoneme_timing/golden_matrix.json (generated by
// scripts/regenerate_timing_fixture.py from src/python_run/piper_plus/timing.py)
// and asserts that the spec-defined cursor-walk algorithm in C++ produces
// the same output as the Python canonical implementation, byte-for-byte.
//
// The spec (docs/spec/phoneme-timing-contract.toml) defines:
//
//   frame_time_ms = (hop_length / sample_rate) * 1000
//   cursor_ms = 0.0
//   for each (duration_frames, phoneme_token):
//       duration_ms = ceil(max(duration_frames, 0.0)) * frame_time_ms
//       start_ms = cursor_ms
//       end_ms   = cursor_ms + duration_ms
//       yield {phoneme, start_ms, end_ms, duration_ms}
//       cursor_ms = end_ms
//
// Note: the production helper piper.cpp:extractTimingsFromDurations operates
// on integer PhonemeIds (skipping PAD/BOS/EOS) and reports times in seconds.
// To stay self-contained (no onnxruntime/espeak link), this test re-implements
// the spec algorithm against the fixture's string tokens and ms timestamps,
// catching drift between the spec, the Python canonical, and the C++ math.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <locale>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include "json.hpp"
#include "timing_format.hpp"
#include "timing_helpers.hpp"

namespace {

namespace fs = std::filesystem;
using nlohmann::json;

// Floating-point tolerance for parity comparison.
// Python computes via float64; our cursor-walk is also float64. A handful of
// ULPs is reasonable; 1e-6 ms is comfortably tighter than any meaningful drift.
constexpr double kAbsTolMs = 1e-6;

struct ComputedEntry {
  std::string phoneme;
  double start_ms;
  double end_ms;
  double duration_ms;
};

struct ComputedResult {
  std::vector<ComputedEntry> phonemes;
  double total_duration_ms;
  int sample_rate;
};

// Spec [calculation] cursor-walk applied verbatim.
ComputedResult computeFromSpec(const std::vector<double>& durations,
                               const std::vector<std::string>& phoneme_tokens,
                               int sample_rate, int hop_length) {
  ComputedResult out;
  out.sample_rate = sample_rate;
  const double frame_time_ms =
      (static_cast<double>(hop_length) / static_cast<double>(sample_rate)) *
      1000.0;

  double cursor_ms = 0.0;
  const size_t n = std::min(durations.size(), phoneme_tokens.size());
  out.phonemes.reserve(n);
  for (size_t i = 0; i < n; ++i) {
    double dur_frames = durations[i];
    if (dur_frames < 0.0) {
      dur_frames = 0.0;  // spec [calculation.negative_handling]
    }
    // spec_version 1.2 [calculation.frame_quantization]: the decoder allocates
    // ceil(d_i) frames, so quantise AFTER the clamp (ceil(-2.0) is -2.0).
    dur_frames = std::ceil(dur_frames);
    const double duration_ms = dur_frames * frame_time_ms;
    ComputedEntry e{phoneme_tokens[i], cursor_ms, cursor_ms + duration_ms,
                    duration_ms};
    out.phonemes.push_back(std::move(e));
    cursor_ms += duration_ms;
  }
  out.total_duration_ms = cursor_ms;
  return out;
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

fs::path findFixturePath() {
  // Allow CI / build systems to override.
  if (const char* env = std::getenv("PIPER_PLUS_TIMING_FIXTURE")) {
    return fs::path(env);
  }

  // Walk upwards from the current working directory looking for the fixture.
  // The CMake test sets WORKING_DIRECTORY to CMAKE_SOURCE_DIR (repo root) for
  // the foreach loop above, but our standalone test runs without that — so be
  // robust to either.
  const fs::path needle = fs::path("tests") / "fixtures" / "phoneme_timing" /
                          "golden_matrix.json";
  fs::path cwd = fs::current_path();
  for (int depth = 0; depth < 8; ++depth) {
    fs::path candidate = cwd / needle;
    if (fs::exists(candidate)) {
      return candidate;
    }
    if (!cwd.has_parent_path() || cwd == cwd.parent_path()) {
      break;
    }
    cwd = cwd.parent_path();
  }
  return needle;  // last resort — will fail open + give a useful error
}

json loadFixture() {
  const fs::path fixture_path = findFixturePath();
  std::ifstream stream(fixture_path);
  EXPECT_TRUE(stream.is_open())
      << "Cannot open phoneme timing fixture: " << fixture_path
      << " (cwd=" << fs::current_path() << "). Set PIPER_PLUS_TIMING_FIXTURE if the "
                                           "default search path doesn't apply.";
  std::stringstream buffer;
  buffer << stream.rdbuf();
  return json::parse(buffer.str());
}

}  // namespace

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// Rendered-output byte parity (issue #716).
//
// Everything above compares PARSED numbers, so the formatting layer -- column
// order, precision, locale, escaping, separators, trailing newline -- was
// unchecked in every runtime until the fixture started carrying the rendered
// text at spec_version 1.2. The moment it did, two defects surfaced at that
// layer: a UTF-8 BOM on C# TSV output, and the C++ CLI emitting eight columns
// led by `phoneme` instead of the contract's four led by `start_ms`.
//
// These cases call the PRODUCTION writers (src/cpp/timing_format.hpp, used by
// piper.cpp:outputTimingsAsTSV / outputTimingsAsSRT) and compare the result
// byte-for-byte with the fixture, which is what the other five runtimes do.
//
// The rows are built from the fixture's millisecond values rather than from
// PhonemeInfo's float32 seconds, deliberately: that isolates the formatting
// from the storage round-trip, which the numeric assertions above already
// cover to kAbsTolMs. Feeding seconds here would make a formatting regression
// and a precision regression indistinguishable.
// ---------------------------------------------------------------------------

std::vector<piper::timing_format::FormatRow> rowsFromFixture(
    const json& expected_phonemes) {
  std::vector<piper::timing_format::FormatRow> rows;
  rows.reserve(expected_phonemes.size());
  for (const auto& entry : expected_phonemes) {
    rows.push_back({entry["phoneme"].get<std::string>(),
                    entry["start_ms"].get<double>(),
                    entry["end_ms"].get<double>(),
                    entry["duration_ms"].get<double>()});
  }
  return rows;
}

// A locale whose numpunct groups thousands, so the writers' locale pinning is
// actually exercised. Hand-rolled rather than named ("en_US.UTF-8") so the
// grouping is identical on every runner regardless of installed locales.
class CommaGroupingNumpunct : public std::numpunct<char> {
 protected:
  char do_thousands_sep() const override { return ','; }
  std::string do_grouping() const override { return "\3"; }
};

TEST(PhonemeTimingParity, TsvMatchesFixtureByteForByte) {
  const auto fixture = loadFixture();
  std::size_t cases_with_tsv = 0;

  for (const auto& test_case : fixture["cases"]) {
    const std::string name = test_case.value("name", "<unnamed>");
    const auto& expected = test_case["expected"];
    if (!expected.contains("tsv")) {
      continue;
    }
    SCOPED_TRACE("case=" + name);
    ++cases_with_tsv;

    std::ostringstream out;
    // Grouping locale on purpose: `1,011.541` is what an unpinned writer
    // produced, and it is not a number to any TSV consumer.
    out.imbue(std::locale(std::locale::classic(), new CommaGroupingNumpunct));
    piper::timing_format::writeTsv(out, rowsFromFixture(expected["phonemes"]));

    EXPECT_EQ(out.str(), expected["tsv"].get<std::string>())
        << "rendered TSV differs from the fixture in case " << name;
  }

  // Anti-vacuity: with no `tsv` field in any case the loop above asserts
  // nothing, which is exactly the state that let the column divergence ship.
  EXPECT_GT(cases_with_tsv, 0u)
      << "no fixture case carries an `expected.tsv` field, so this test "
         "compared nothing -- regenerate with scripts/regenerate_timing_fixture.py";
}

TEST(PhonemeTimingParity, SrtMatchesFixtureByteForByte) {
  const auto fixture = loadFixture();
  std::size_t cases_with_srt = 0;

  for (const auto& test_case : fixture["cases"]) {
    const std::string name = test_case.value("name", "<unnamed>");
    const auto& expected = test_case["expected"];
    if (!expected.contains("srt")) {
      continue;
    }
    SCOPED_TRACE("case=" + name);
    ++cases_with_srt;

    std::ostringstream out;
    // The cue index is streamed as an integer, so the grouping locale is what
    // turned cue 1000 into "1,000".
    out.imbue(std::locale(std::locale::classic(), new CommaGroupingNumpunct));
    piper::timing_format::writeSrt(out, rowsFromFixture(expected["phonemes"]));

    EXPECT_EQ(out.str(), expected["srt"].get<std::string>())
        << "rendered SRT differs from the fixture in case " << name;
  }

  EXPECT_GT(cases_with_srt, 0u)
      << "no fixture case carries an `expected.srt` field, so this test "
         "compared nothing";
}

// The contract pins the header string itself. Asserting it separately gives a
// one-line failure when only the header moves, instead of a whole-file diff.
TEST(PhonemeTimingParity, TsvHeaderMatchesContract) {
  std::ostringstream out;
  piper::timing_format::writeTsv(out, {});
  EXPECT_EQ(out.str(), "start_ms\tend_ms\tduration_ms\tphoneme\n");
}

// The SRT cue index is streamed as an integer, so a grouping locale turns cue
// 1000 into "1,000" -- not an integer to any SRT parser. No fixture case is
// long enough to reach the boundary (the longest has 60 entries), so removing
// the writer's locale guard passed every byte-parity comparison above. This
// case is the one that fails: 1000 cues, and the index must stay plain.
TEST(PhonemeTimingParity, SrtCueIndexPastOneThousandHasNoGroupingSeparator) {
  std::vector<piper::timing_format::FormatRow> rows;
  rows.reserve(1000);
  for (int i = 0; i < 1000; ++i) {
    const double start = static_cast<double>(i);
    rows.push_back({"a", start, start + 1.0, 1.0});
  }

  std::ostringstream out;
  out.imbue(std::locale(std::locale::classic(), new CommaGroupingNumpunct));
  piper::timing_format::writeSrt(out, rows);

  // Only the index lines are checked for a comma: the timestamp format is
  // "HH:MM:SS,mmm", so a comma there is the contract's decimal separator, not
  // a grouping artifact. Cue blocks are "index\ntimestamps\nphoneme\n\n",
  // so the index is every 4th line.
  std::vector<std::string> indices;
  {
    std::istringstream lines(out.str());
    std::string line;
    for (std::size_t n = 0; std::getline(lines, line); ++n) {
      if (n % 4 == 0) {
        indices.push_back(line);
      }
    }
  }

  ASSERT_EQ(indices.size(), 1000u);
  EXPECT_EQ(indices.front(), "1");
  EXPECT_EQ(indices.back(), "1000")
      << "cue 1000 did not come out plain, so either the index is grouped "
         "(the writer is inheriting the caller's locale instead of pinning "
         "the classic one) or the cue layout changed";
  for (std::size_t i = 0; i < indices.size(); ++i) {
    EXPECT_EQ(indices[i].find(','), std::string::npos)
        << "cue index " << (i + 1) << " ('" << indices[i]
        << "') carries a digit-group separator";
  }
}

// [output_formats.tsv] escape_tab_in_phoneme / escape_newline_in_phoneme.
// A token carrying a literal tab or newline would invent a column or a row.
TEST(PhonemeTimingParity, TsvEscapesTabAndNewlineInPhoneme) {
  std::ostringstream out;
  piper::timing_format::writeTsv(
      out, {{"a\tb", 0.0, 1.0, 1.0}, {"c\nd", 1.0, 2.0, 1.0}});

  const std::string text = out.str();
  EXPECT_NE(text.find("a\\tb"), std::string::npos);
  EXPECT_NE(text.find("c\\nd"), std::string::npos);
  // Header + 2 rows, each terminated: exactly 3 newlines, and no stray tab
  // beyond the 3 separators per row plus the 3 in the header.
  EXPECT_EQ(std::count(text.begin(), text.end(), '\n'), 3);
  EXPECT_EQ(std::count(text.begin(), text.end(), '\t'), 9);
}

// Smoke test: fixture is loadable and at the expected schema version.
TEST(PhonemeTimingParity, FixtureLoadsAndIsSchemaV1) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("schema_version"));
  EXPECT_EQ(fixture["schema_version"].get<int>(), 1);
  ASSERT_TRUE(fixture.contains("cases"));
  EXPECT_GT(fixture["cases"].size(), 0u);
}

// One assertion per case × per phoneme — produces a clear failure message
// when a single case drifts.
TEST(PhonemeTimingParity, AllCasesMatchPythonCanonical) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("cases"));

  for (const auto& test_case : fixture["cases"]) {
    const std::string name = test_case.value("name", "<unnamed>");
    SCOPED_TRACE("case=" + name);

    const auto& inputs = test_case["inputs"];
    std::vector<double> durations;
    for (const auto& d : inputs["durations"]) {
      durations.push_back(d.get<double>());
    }
    std::vector<std::string> phoneme_tokens;
    for (const auto& t : inputs["phoneme_tokens"]) {
      phoneme_tokens.push_back(t.get<std::string>());
    }
    const int sample_rate = inputs["sample_rate"].get<int>();
    const int hop_length = inputs["hop_length"].get<int>();

    const ComputedResult got =
        computeFromSpec(durations, phoneme_tokens, sample_rate, hop_length);

    const auto& expected = test_case["expected"];
    EXPECT_EQ(got.sample_rate, expected["sample_rate"].get<int>());

    EXPECT_NEAR(got.total_duration_ms,
                expected["total_duration_ms"].get<double>(), kAbsTolMs)
        << "total_duration_ms mismatch in case " << name;

    const auto& expected_phonemes = expected["phonemes"];
    ASSERT_EQ(got.phonemes.size(), expected_phonemes.size())
        << "phoneme count mismatch in case " << name;

    for (size_t i = 0; i < got.phonemes.size(); ++i) {
      SCOPED_TRACE("phoneme[" + std::to_string(i) + "]");
      EXPECT_EQ(got.phonemes[i].phoneme,
                expected_phonemes[i]["phoneme"].get<std::string>());
      EXPECT_NEAR(got.phonemes[i].start_ms,
                  expected_phonemes[i]["start_ms"].get<double>(), kAbsTolMs);
      EXPECT_NEAR(got.phonemes[i].end_ms,
                  expected_phonemes[i]["end_ms"].get<double>(), kAbsTolMs);
      EXPECT_NEAR(got.phonemes[i].duration_ms,
                  expected_phonemes[i]["duration_ms"].get<double>(), kAbsTolMs);
    }
  }
}

// Spec [calculation.negative_handling]: negative durations are clamped to 0.
TEST(PhonemeTimingParity, NegativeDurationsClampedExplicitly) {
  const std::vector<double> durations = {3.0, -2.0, 5.0};
  const std::vector<std::string> tokens = {"a", "b", "c"};
  const int sample_rate = 22050;
  const int hop_length = 256;

  const ComputedResult got =
      computeFromSpec(durations, tokens, sample_rate, hop_length);

  ASSERT_EQ(got.phonemes.size(), 3u);
  EXPECT_EQ(got.phonemes[1].phoneme, "b");
  EXPECT_DOUBLE_EQ(got.phonemes[1].duration_ms, 0.0);
  // Cursor must not regress: 'c' starts where 'b' ended.
  EXPECT_DOUBLE_EQ(got.phonemes[2].start_ms, got.phonemes[1].end_ms);
}

// Spec: empty input → empty result, total_duration_ms = 0.
TEST(PhonemeTimingParity, EmptyInputProducesEmptyResult) {
  const ComputedResult got = computeFromSpec({}, {}, 22050, 256);
  EXPECT_TRUE(got.phonemes.empty());
  EXPECT_DOUBLE_EQ(got.total_duration_ms, 0.0);
  EXPECT_EQ(got.sample_rate, 22050);
}

// ---------------------------------------------------------------------------
// Reverse-map parity (issue #698).
//
// The cases above start from resolved token strings, so nothing in them says
// how phoneme_id_map is turned back into names. The contract said first-wins
// without defining "first", and the runtimes split three/three -- python / js
// / csharp iterated in insertion order, cpp / rust / go sorted. Every shipped
// model is collision-free, so all six agreed byte-for-byte and no test could
// see it.
//
// PhonemeIdMap is std::map<char32_t, ...>, so only single-codepoint keys can
// be represented -- which is why the fixture uses them. A multi-codepoint key
// is reported rather than skipped: it would mean the fixture has grown a case
// this runtime cannot express, and silently passing over it is how a gap gets
// missed.
// ---------------------------------------------------------------------------

TEST(PhonemeTimingParity, ReverseMapCasesMatchTheFixture) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("reverse_map_cases"))
      << "fixture has no reverse_map_cases; regenerate with "
         "scripts/regenerate_timing_fixture.py";
  const auto& cases = fixture["reverse_map_cases"];
  ASSERT_GT(cases.size(), 0u);

  for (const auto& test_case : cases) {
    const std::string name = test_case.value("name", "<unnamed>");
    SCOPED_TRACE("case=" + name);

    const auto& inputs = test_case["inputs"];
    piper::PhonemeIdMap idMap;
    for (const auto& [key, ids] : inputs["phoneme_id_map"].items()) {
      ASSERT_TRUE(piper::isSingleCodepointUtf8(key))
          << "key " << key << " is not a single codepoint, which "
          << "PhonemeIdMap (std::map<char32_t, ...>) cannot represent";
      const char32_t cp = piper::firstCodepointUtf8(key);
      for (const auto& id : ids) {
        idMap[cp].push_back(id.get<piper::PhonemeId>());
      }
    }

    // The PUA table is built in rather than injected here, exactly as the
    // production walk uses it, so a case whose `pua_names` disagrees with
    // puaToPhonemeMap() would be comparing two different tables. Assert the
    // agreement instead of assuming it.
    if (inputs.contains("pua_names") && inputs["pua_names"].is_object()) {
      const auto& pua = piper::puaToPhonemeMap();
      for (const auto& [key, name_json] : inputs["pua_names"].items()) {
        ASSERT_TRUE(piper::isSingleCodepointUtf8(key));
        const auto it = pua.find(piper::firstCodepointUtf8(key));
        ASSERT_NE(it, pua.end())
            << "the fixture names a PUA codepoint that puaToPhonemeMap() does "
               "not; the fixture and the PUA consistency gate disagree";
        EXPECT_EQ(it->second, name_json.get<std::string>());
      }
    }

    const auto got = piper::buildPhonemeIdToStringMap(idMap);

    const auto& expected = test_case["expected"];
    EXPECT_EQ(got.size(), expected.size());
    for (const auto& [id_str, want] : expected.items()) {
      const auto id = static_cast<piper::PhonemeId>(std::stoll(id_str));
      const auto it = got.find(id);
      ASSERT_NE(it, got.end()) << "id " << id << " missing from the reverse map";
      EXPECT_EQ(it->second, want.get<std::string>());
    }
  }
}

// Anti-vacuity: without a MIRRORED colliding case, key order is unobservable.
// A collision-free map resolves identically under any iteration order, and a
// single colliding map can be satisfied by a runtime that happens to receive
// its keys already sorted.
//
// nlohmann::json does NOT preserve object key order -- its default object
// type is std::map, which sorts -- so the file is re-parsed here as
// ordered_json (available since 3.9; the bundled copy is 3.11.2). Without
// that, both spellings of the mirrored pair collapse to the same sorted key
// list and this check cannot distinguish them; measured, it failed before the
// switch.
TEST(PhonemeTimingParity, ReverseMapCasesIncludeAMirroredCollision) {
  const fs::path path = findFixturePath();
  std::ifstream in(path);
  ASSERT_TRUE(in.good()) << "cannot open " << path;
  std::stringstream buffer;
  buffer << in.rdbuf();
  const auto fixture = nlohmann::ordered_json::parse(buffer.str());
  ASSERT_TRUE(fixture.contains("reverse_map_cases"));

  std::map<std::string, std::set<std::string>> orders_by_keyset;
  for (const auto& test_case : fixture["reverse_map_cases"]) {
    const auto& idMap = test_case["inputs"]["phoneme_id_map"];
    std::set<long long> seen;
    bool collides = false;
    std::vector<std::string> keys;
    for (const auto& [key, ids] : idMap.items()) {
      keys.push_back(key);
      for (const auto& id : ids) {
        if (!seen.insert(id.get<long long>()).second) {
          collides = true;
        }
      }
    }
    if (!collides) {
      continue;
    }
    std::vector<std::string> sorted_keys = keys;
    std::sort(sorted_keys.begin(), sorted_keys.end());
    const auto join = [](const std::vector<std::string>& parts) {
      std::string out;
      for (const auto& part : parts) {
        out += part;
        out += '\x01';
      }
      return out;
    };
    orders_by_keyset[join(sorted_keys)].insert(join(keys));
  }

  bool mirrored = false;
  for (const auto& [keyset, orders] : orders_by_keyset) {
    if (orders.size() >= 2) {
      mirrored = true;
    }
  }
  EXPECT_TRUE(mirrored)
      << "no colliding key set is written in two different orders, so these "
         "cases cannot detect a runtime that iterates phoneme_id_map in "
         "insertion order";
}
