/**
 * test_speaker_embedding_inference.cpp — Issue #426 C++ integration test
 *
 * Verifies that the C++ runtime (piper.cpp:buildInputTensors) feeds
 * zero embedding + mask=0 when a model declares speaker_embedding /
 * speaker_embedding_mask but the caller does not provide an embedding.
 * Without this, ORT raises:
 *   "Required inputs (['speaker_embedding', 'speaker_embedding_mask'])
 *    are missing from input feed".
 *
 * Fixture: `tests/fixtures/mb_istft_speaker_embedding/model.onnx` +
 *          `model.onnx.json` (generated by build_fixture.py).
 * Auto-skips when the fixture is unavailable so this test can be added
 * to the existing matrix without breaking environments that lack
 * Python / torch.
 */

#include <gtest/gtest.h>
#include <filesystem>
#include "../piper.hpp"

namespace fs = std::filesystem;

namespace {

struct FixturePaths {
    bool found = false;
    std::string model;
    std::string config;
};

FixturePaths find_fixture() {
    const std::vector<std::string> search_paths = {
        "tests/fixtures/mb_istft_speaker_embedding/model.onnx",
        "../tests/fixtures/mb_istft_speaker_embedding/model.onnx",
        "../../tests/fixtures/mb_istft_speaker_embedding/model.onnx",
        "../../../tests/fixtures/mb_istft_speaker_embedding/model.onnx",
        "../../../../tests/fixtures/mb_istft_speaker_embedding/model.onnx",
    };
    for (const auto& p : search_paths) {
        if (fs::exists(p)) {
            std::string cfg = p + ".json";
            if (fs::exists(cfg)) {
                return {true, p, cfg};
            }
        }
    }
    return {};
}

}  // namespace

class SpeakerEmbeddingInferenceTest : public ::testing::Test {
protected:
    piper::PiperConfig config;
    piper::Voice voice;
    bool fixture_found = false;

    void SetUp() override {
        auto paths = find_fixture();
        if (!paths.found) {
            GTEST_SKIP() << "speaker_embedding fixture not found at "
                            "tests/fixtures/mb_istft_speaker_embedding/model.onnx "
                            "— run `python tests/fixtures/mb_istft_speaker_embedding/"
                            "build_fixture.py` to generate it.";
            return;
        }
        fixture_found = true;

        std::optional<piper::SpeakerId> speakerId;
        loadVoice(config, paths.model, paths.config, voice, speakerId, "cpu");
        piper::initialize(config);
    }

    void TearDown() override {
        if (fixture_found) {
            piper::terminate(config);
        }
    }
};

// ----------------------------------------------------------------------------
// Issue #426: ModelSession must auto-detect speaker_embedding declaration.
// ----------------------------------------------------------------------------

TEST_F(SpeakerEmbeddingInferenceTest, DetectsSpeakerEmbeddingInput) {
    if (!fixture_found) return;
    EXPECT_TRUE(voice.session.hasSpeakerEmbeddingInput)
        << "ModelSession failed to detect speaker_embedding declared by "
           "the fixture (Issue #426 regression — the input-scan loop in "
           "piper.cpp must set hasSpeakerEmbeddingInput=true).";
}

TEST_F(SpeakerEmbeddingInferenceTest, DetectsSpeakerEmbeddingDim) {
    if (!fixture_found) return;
    // build_fixture.py uses spk_emb_dim = 64 for size minimisation; the
    // C++ session must read this from the ONNX input shape (not assume
    // the ECAPA-TDNN canonical 256).
    EXPECT_EQ(voice.session.speakerEmbeddingDim, 64)
        << "speakerEmbeddingDim must come from the model's input shape; "
           "a hard-coded 256 would fail this fixture.";
}

// ----------------------------------------------------------------------------
// Issue #426: synthesize must run end-to-end with zero+mask=0 fallback.
// ----------------------------------------------------------------------------

TEST_F(SpeakerEmbeddingInferenceTest, SynthesizeWithoutExternalEmbeddingProducesAudio) {
    if (!fixture_found) return;
    // phonemesToAudio accepts a Phoneme vector and runs the full pipeline
    // including buildInputTensors. The fixture has phoneme_id_map[i]=[i]
    // so we can use any character whose code point < 50.
    std::vector<piper::Phoneme> phonemes;
    for (char32_t cp : {U'a', U'b', U'c', U'd', U'e'}) {
        phonemes.push_back(cp);
    }

    std::vector<int16_t> audioBuffer;
    piper::SynthesisResult result;

    ASSERT_NO_THROW(
        piper::phonemesToAudio(config, voice, phonemes, audioBuffer, result)
    ) << "Issue #426 regression: synthesize must not raise "
         "\"Required inputs missing\" when speaker_embedding is declared.";

    EXPECT_GT(audioBuffer.size(), 0u)
        << "audio buffer must be non-empty (Issue #426 fallback regression?)";

    // Sanity: not all samples are zero (model degenerated).
    bool any_non_zero = false;
    for (auto s : audioBuffer) {
        if (s != 0) {
            any_non_zero = true;
            break;
        }
    }
    EXPECT_TRUE(any_non_zero)
        << "all-zero output indicates the model received bad inputs";
}

int main(int argc, char** argv) {
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
