// Cross-runtime Speaker Encoder mel parity test.
//
// Loads test/fixtures/speaker_encoder_golden.json (generated by
// test/generate_speaker_encoder_golden.py from the Python torchaudio reference)
// and asserts that the spec-defined mel feature pipeline (Hann window + slaney
// mel filterbank + STFT magnitude → log-mel) produces the same output as the
// Python canonical implementation.
//
// Why this lives in the test file (not in the production C API):
//
// The C API speaker_encoder symbols (piper_plus_speaker_encoder_*) are
// EXPERIMENTAL and currently return an error — the implementation is reserved
// for forward compatibility. This test re-implements the spec algorithm
// independently (matching the Rust/Go/C# parity tests) so that:
//
//   1. The canonical Python fixture itself can be detected for drift.
//   2. When the C++ production implementation lands, it must match these
//      same fixture values, gating cross-runtime parity.
//
// Algorithm is identical to src/rust/piper-core/tests/test_speaker_encoder_golden.rs
// — pure floating-point math, no FFT or onnxruntime dependency.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "json.hpp"

namespace {

namespace fs = std::filesystem;
using nlohmann::json;

constexpr int    kMelSampleRate = 16000;
constexpr int    kMelNFft       = 400;
constexpr int    kMelHopLength  = 160;
constexpr int    kMelNMels      = 80;
constexpr float  kMelFmin       = 20.0f;
constexpr float  kMelFmax       = 7600.0f;

constexpr double kPi              = 3.14159265358979323846;
constexpr double kAbsTolHann       = 1e-6;
constexpr double kRelTolFilterbank = 0.02;
// 0.02 for sampled L2 (matches Rust/C#/Go canonical).
constexpr double kRelTolMel        = 0.02;
// 0.03 for corner-cell parity (matches Rust/C# canonical; relaxed for
// cross-platform DFT rounding e.g. MSVC vs LLVM / ARM64 macOS).
constexpr double kRelTolMelCorner  = 0.03;

// ---------------------------------------------------------------------------
// Spec algorithm — pure functions, no production code dependency.
// (Identical to src/rust/piper-core/tests/test_speaker_encoder_golden.rs.)
// ---------------------------------------------------------------------------

float hzToMel(float hz) {
  return 2595.0f * std::log10(1.0f + hz / 700.0f);
}

float melToHz(float mel) {
  return 700.0f * (std::pow(10.0f, mel / 2595.0f) - 1.0f);
}

std::vector<float> hannWindow(std::size_t length) {
  std::vector<float> w(length);
  for (std::size_t n = 0; n < length; ++n) {
    w[n] = static_cast<float>(
        0.5 * (1.0 - std::cos(2.0 * kPi * static_cast<double>(n) /
                              static_cast<double>(length))));
  }
  return w;
}

std::vector<float> createMelFilterbank() {
  const std::size_t fft_bins = kMelNFft / 2 + 1;
  std::vector<float> fb(static_cast<std::size_t>(kMelNMels) * fft_bins, 0.0f);

  const float mel_fmin = hzToMel(kMelFmin);
  const float mel_fmax = hzToMel(kMelFmax);

  std::vector<float> mel_points(kMelNMels + 2);
  for (int i = 0; i <= kMelNMels + 1; ++i) {
    mel_points[i] =
        mel_fmin +
        (mel_fmax - mel_fmin) * static_cast<float>(i) /
            static_cast<float>(kMelNMels + 1);
  }

  std::vector<float> bin_points(kMelNMels + 2);
  for (int i = 0; i < kMelNMels + 2; ++i) {
    const float hz = melToHz(mel_points[i]);
    bin_points[i] = hz * static_cast<float>(kMelNFft) /
                    static_cast<float>(kMelSampleRate);
  }

  for (int m = 0; m < kMelNMels; ++m) {
    std::size_t left   = static_cast<std::size_t>(std::floor(bin_points[m]));
    std::size_t center = static_cast<std::size_t>(std::floor(bin_points[m + 1]));
    std::size_t right  = static_cast<std::size_t>(std::floor(bin_points[m + 2]));

    if (left == center && center == right) {
      center = std::min(center + 1, fft_bins - 1);
      right  = std::min(right + 2, fft_bins - 1);
    } else if (left == center) {
      center = std::min(center + 1, fft_bins - 1);
    }
    if (center == right) {
      right = std::min(right + 1, fft_bins - 1);
    }

    for (std::size_t k = left; k < center; ++k) {
      if (center > left) {
        fb[m * fft_bins + k] =
            static_cast<float>(k - left) / static_cast<float>(center - left);
      }
    }
    for (std::size_t k = center; k < right; ++k) {
      if (right > center) {
        fb[m * fft_bins + k] =
            static_cast<float>(right - k) / static_cast<float>(right - center);
      }
    }
    if (center < fft_bins) {
      fb[m * fft_bins + center] =
          std::max(fb[m * fft_bins + center], 1.0f);
    }
  }

  return fb;
}

std::vector<float> computeMelSpectrogram(const std::vector<float>& samples) {
  const std::vector<float> mel_filters = createMelFilterbank();
  const std::vector<float> window      = hannWindow(kMelNFft);

  const std::size_t n_frames =
      samples.size() >= static_cast<std::size_t>(kMelNFft)
          ? (samples.size() - kMelNFft) / kMelHopLength + 1
          : 0;

  const std::size_t fft_bins = kMelNFft / 2 + 1;
  // Frame-major layout (matching WASM/Rust/Go/C# canonical)
  std::vector<float> mel_spec(
      n_frames * static_cast<std::size_t>(kMelNMels), 0.0f);

  std::vector<float> power_spec(fft_bins);
  for (std::size_t frame = 0; frame < n_frames; ++frame) {
    const std::size_t start = frame * kMelHopLength;
    for (std::size_t k = 0; k < fft_bins; ++k) {
      float real = 0.0f;
      float imag = 0.0f;
      const float freq =
          -2.0f * static_cast<float>(kPi) * static_cast<float>(k) /
          static_cast<float>(kMelNFft);
      for (int n = 0; n < kMelNFft; ++n) {
        const float sample =
            (start + n < samples.size())
                ? samples[start + n] * window[n]
                : 0.0f;
        const float angle = freq * static_cast<float>(n);
        real += sample * std::cos(angle);
        imag += sample * std::sin(angle);
      }
      power_spec[k] = real * real + imag * imag;
    }

    for (int mel_idx = 0; mel_idx < kMelNMels; ++mel_idx) {
      float energy = 0.0f;
      for (std::size_t k = 0; k < fft_bins; ++k) {
        energy += mel_filters[mel_idx * fft_bins + k] * power_spec[k];
      }
      mel_spec[frame * kMelNMels + mel_idx] =
          std::log(std::max(energy, 1e-10f));
    }
  }

  // Per-band CMVN (global mean subtraction across all frames)
  // Use f32 accumulation to match Rust/Go/C# canonical reference exactly.
  if (n_frames > 0) {
    for (int mel_idx = 0; mel_idx < kMelNMels; ++mel_idx) {
      float sum = 0.0f;
      for (std::size_t frame = 0; frame < n_frames; ++frame) {
        sum += mel_spec[frame * kMelNMels + mel_idx];
      }
      const float mean = sum / static_cast<float>(n_frames);
      for (std::size_t frame = 0; frame < n_frames; ++frame) {
        mel_spec[frame * kMelNMels + mel_idx] -= mean;
      }
    }
  }

  return mel_spec;
}

std::vector<float> generateSine(float freq_hz, float duration_s, int sr) {
  const std::size_t n =
      static_cast<std::size_t>(duration_s * static_cast<float>(sr));
  std::vector<float> samples(n);
  for (std::size_t i = 0; i < n; ++i) {
    samples[i] = std::sin(2.0f * static_cast<float>(kPi) * freq_hz *
                          static_cast<float>(i) / static_cast<float>(sr));
  }
  return samples;
}

std::vector<float> generateMultitone(const std::vector<float>& freqs,
                                     float duration_s, int sr) {
  const std::size_t n =
      static_cast<std::size_t>(duration_s * static_cast<float>(sr));
  std::vector<float> samples(n, 0.0f);
  for (float f : freqs) {
    for (std::size_t i = 0; i < n; ++i) {
      samples[i] += std::sin(2.0f * static_cast<float>(kPi) * f *
                             static_cast<float>(i) / static_cast<float>(sr));
    }
  }
  float peak = 0.0f;
  for (float s : samples) {
    peak = std::max(peak, std::fabs(s));
  }
  if (peak > 0.0f) {
    for (float& s : samples) {
      s /= peak;
    }
  }
  return samples;
}

double relativeL2(const std::vector<float>& a,
                  const std::vector<double>& b) {
  if (a.size() != b.size()) {
    return std::numeric_limits<double>::infinity();
  }
  double diff_sq = 0.0;
  double ref_sq  = 0.0;
  for (std::size_t i = 0; i < a.size(); ++i) {
    const double d = static_cast<double>(a[i]) - b[i];
    diff_sq += d * d;
    ref_sq += b[i] * b[i];
  }
  if (ref_sq < 1e-20) {
    return std::sqrt(diff_sq);
  }
  return std::sqrt(diff_sq / ref_sq);
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

fs::path findFixturePath() {
  if (const char* env = std::getenv("PIPER_SPEAKER_ENCODER_FIXTURE")) {
    return fs::path(env);
  }
  const fs::path needle =
      fs::path("test") / "fixtures" / "speaker_encoder_golden.json";
  fs::path cwd = fs::current_path();
  for (int depth = 0; depth < 8; ++depth) {
    fs::path candidate = cwd / needle;
    if (fs::exists(candidate)) {
      return candidate;
    }
    if (!cwd.has_parent_path() || cwd == cwd.parent_path()) {
      break;
    }
    cwd = cwd.parent_path();
  }
  return needle;
}

json loadFixture() {
  const fs::path fixture_path = findFixturePath();
  std::ifstream stream(fixture_path);
  EXPECT_TRUE(stream.is_open())
      << "Cannot open speaker encoder fixture: " << fixture_path
      << " (cwd=" << fs::current_path() << "). Set "
         "PIPER_SPEAKER_ENCODER_FIXTURE if the default search path doesn't "
         "apply.";
  std::stringstream buffer;
  buffer << stream.rdbuf();
  return json::parse(buffer.str());
}

const json& findCase(const json& fixture, const std::string& id) {
  for (const auto& tc : fixture.at("test_cases")) {
    if (tc.value("id", std::string()) == id) {
      return tc;
    }
  }
  ADD_FAILURE() << "Test case not found in fixture: " << id;
  static const json empty = json::object();
  return empty;
}

}  // namespace

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

TEST(SpeakerEncoderParity, FixtureLoadsAndParamsMatch) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("mel_params"));
  const auto& p = fixture["mel_params"];
  EXPECT_EQ(p["sr"].get<int>(), kMelSampleRate);
  EXPECT_EQ(p["n_fft"].get<int>(), kMelNFft);
  EXPECT_EQ(p["hop_length"].get<int>(), kMelHopLength);
  EXPECT_EQ(p["n_mels"].get<int>(), kMelNMels);
  EXPECT_NEAR(p["fmin"].get<float>(), kMelFmin, 1e-3f);
  EXPECT_NEAR(p["fmax"].get<float>(), kMelFmax, 1e-3f);
}

TEST(SpeakerEncoderParity, HannWindowMatchesGolden) {
  const auto fixture = loadFixture();
  const auto& hw = fixture["hann_window"];
  const std::size_t length = hw["length"].get<std::size_t>();
  const std::vector<float> w = hannWindow(length);

  ASSERT_EQ(w.size(), length);

  // First 5 samples
  const auto& first_5 = hw["first_5"];
  ASSERT_EQ(first_5.size(), 5u);
  for (std::size_t i = 0; i < 5; ++i) {
    const double expected = first_5[i].get<double>();
    EXPECT_NEAR(static_cast<double>(w[i]), expected, kAbsTolHann)
        << "hann_window[" << i << "]";
  }

  // Last 5 samples
  const auto& last_5 = hw["last_5"];
  ASSERT_EQ(last_5.size(), 5u);
  for (std::size_t i = 0; i < 5; ++i) {
    const double expected = last_5[i].get<double>();
    const std::size_t idx = length - 5 + i;
    EXPECT_NEAR(static_cast<double>(w[idx]), expected, kAbsTolHann)
        << "hann_window[" << idx << "]";
  }

  // Mid value
  const double mid_expected = hw["mid_value"].get<double>();
  EXPECT_NEAR(static_cast<double>(w[length / 2]), mid_expected, kAbsTolHann);
}

TEST(SpeakerEncoderParity, MelFilterbankShape) {
  const auto fixture = loadFixture();
  const auto& fb_meta = fixture["mel_filterbank"];
  const auto shape = fb_meta["shape"];
  ASSERT_EQ(shape.size(), 2u);
  EXPECT_EQ(shape[0].get<int>(), kMelNMels);
  EXPECT_EQ(shape[1].get<int>(), kMelNFft / 2 + 1);

  const std::vector<float> fb = createMelFilterbank();
  EXPECT_EQ(fb.size(),
            static_cast<std::size_t>(kMelNMels) * (kMelNFft / 2 + 1));
}

TEST(SpeakerEncoderParity, MelFilterbankBandSumsMatchGolden) {
  const auto fixture = loadFixture();
  const auto& expected_band_sums = fixture["mel_filterbank"]["band_sums"];
  ASSERT_EQ(expected_band_sums.size(), static_cast<std::size_t>(kMelNMels));

  const std::vector<float> fb = createMelFilterbank();
  const std::size_t fft_bins = kMelNFft / 2 + 1;

  for (int m = 0; m < kMelNMels; ++m) {
    double sum = 0.0;
    for (std::size_t k = 0; k < fft_bins; ++k) {
      sum += fb[m * fft_bins + k];
    }
    const double expected = expected_band_sums[m].get<double>();
    const double rel_err =
        (std::fabs(expected) > 1e-10) ? std::fabs((sum - expected) / expected)
                                      : std::fabs(sum - expected);
    EXPECT_LT(rel_err, kRelTolFilterbank)
        << "filterbank band[" << m << "]: expected " << expected << ", got "
        << sum;
  }
}

TEST(SpeakerEncoderParity, MelFilterbankTotalSumMatchesGolden) {
  const auto fixture = loadFixture();
  const double expected_total =
      fixture["mel_filterbank"]["total_sum"].get<double>();

  const std::vector<float> fb = createMelFilterbank();
  double total = 0.0;
  for (float v : fb) {
    total += v;
  }
  const double rel_err = std::fabs((total - expected_total) / expected_total);
  EXPECT_LT(rel_err, kRelTolFilterbank)
      << "filterbank total: expected " << expected_total << ", got " << total;
}

TEST(SpeakerEncoderParity, Sine440HzMelShapeMatches) {
  const auto fixture = loadFixture();
  const auto& tc = findCase(fixture, "sine_440hz_1s");
  ASSERT_TRUE(tc.contains("expected_mel_shape"));

  const std::vector<float> audio = generateSine(440.0f, 1.0f, kMelSampleRate);
  EXPECT_EQ(audio.size(), tc["audio_samples_count"].get<std::size_t>());

  const std::vector<float> mel = computeMelSpectrogram(audio);
  const std::size_t n_frames = mel.size() / kMelNMels;

  const auto& shape = tc["expected_mel_shape"];
  EXPECT_EQ(shape[0].get<int>(), kMelNMels);
  EXPECT_EQ(shape[1].get<std::size_t>(), n_frames);
  EXPECT_EQ(mel.size(), static_cast<std::size_t>(kMelNMels) * n_frames);
}

TEST(SpeakerEncoderParity, Sine440HzMelCornersMatch) {
  const auto fixture = loadFixture();
  const auto& tc = findCase(fixture, "sine_440hz_1s");
  ASSERT_TRUE(tc.contains("mel_corner_values"));
  const auto& corners = tc["mel_corner_values"];

  const std::vector<float> audio = generateSine(440.0f, 1.0f, kMelSampleRate);
  const std::vector<float> mel = computeMelSpectrogram(audio);
  const std::size_t n_frames = mel.size() / kMelNMels;

  auto check = [](const char* name, double actual, double expected) {
    const double rel = (std::fabs(expected) > 1e-10)
                           ? std::fabs((actual - expected) / expected)
                           : std::fabs(actual - expected);
    EXPECT_LT(rel, kRelTolMelCorner) << name << ": expected " << expected
                                      << ", got " << actual;
  };

  check("top_left", static_cast<double>(mel[0 * kMelNMels + 0]),
        corners["top_left"].get<double>());
  check("top_right",
        static_cast<double>(mel[(n_frames - 1) * kMelNMels + 0]),
        corners["top_right"].get<double>());
  check("bottom_left",
        static_cast<double>(mel[0 * kMelNMels + (kMelNMels - 1)]),
        corners["bottom_left"].get<double>());
  check("bottom_right",
        static_cast<double>(
            mel[(n_frames - 1) * kMelNMels + (kMelNMels - 1)]),
        corners["bottom_right"].get<double>());
}

TEST(SpeakerEncoderParity, Sine440HzMelSampledMatches) {
  const auto fixture = loadFixture();
  const auto& tc = findCase(fixture, "sine_440hz_1s");
  ASSERT_TRUE(tc.contains("mel_sampled_every_10"));

  const std::vector<float> audio = generateSine(440.0f, 1.0f, kMelSampleRate);
  const std::vector<float> mel = computeMelSpectrogram(audio);

  std::vector<float> sampled;
  sampled.reserve(mel.size() / 10 + 1);
  for (std::size_t i = 0; i < mel.size(); i += 10) {
    sampled.push_back(mel[i]);
  }

  std::vector<double> expected;
  expected.reserve(tc["mel_sampled_every_10"].size());
  for (const auto& v : tc["mel_sampled_every_10"]) {
    expected.push_back(v.get<double>());
  }

  const double l2 = relativeL2(sampled, expected);
  EXPECT_LT(l2, kRelTolMel)
      << "sine_440hz_1s sampled L2 distance " << l2 << " exceeds tolerance";
}

TEST(SpeakerEncoderParity, Sine1000HzMelCornersMatch) {
  const auto fixture = loadFixture();
  const auto& tc = findCase(fixture, "sine_1000hz_0.5s");
  ASSERT_TRUE(tc.contains("mel_corner_values"));
  const auto& corners = tc["mel_corner_values"];

  const std::vector<float> audio = generateSine(1000.0f, 0.5f, kMelSampleRate);
  const std::vector<float> mel = computeMelSpectrogram(audio);
  const std::size_t n_frames = mel.size() / kMelNMels;
  std::fprintf(stderr, "DBG1000 n_frames=%zu mel.size=%zu\n", n_frames, mel.size());
  std::fprintf(stderr, "DBG1000 tl=%.7f tr=%.7f bl=%.7f br=%.7f\n",
               mel[0], mel[(n_frames - 1) * kMelNMels],
               mel[kMelNMels - 1],
               mel[(n_frames - 1) * kMelNMels + (kMelNMels - 1)]);

  auto check = [](const char* name, double actual, double expected) {
    const double rel = (std::fabs(expected) > 1e-10)
                           ? std::fabs((actual - expected) / expected)
                           : std::fabs(actual - expected);
    EXPECT_LT(rel, kRelTolMelCorner) << name << ": expected " << expected
                                      << ", got " << actual;
  };

  check("top_left", static_cast<double>(mel[0 * kMelNMels + 0]),
        corners["top_left"].get<double>());
  check("top_right",
        static_cast<double>(mel[(n_frames - 1) * kMelNMels + 0]),
        corners["top_right"].get<double>());
  check("bottom_left",
        static_cast<double>(mel[0 * kMelNMels + (kMelNMels - 1)]),
        corners["bottom_left"].get<double>());
  check("bottom_right",
        static_cast<double>(
            mel[(n_frames - 1) * kMelNMels + (kMelNMels - 1)]),
        corners["bottom_right"].get<double>());
}

TEST(SpeakerEncoderParity, MultitoneMelCornersMatch) {
  const auto fixture = loadFixture();
  const auto& tc = findCase(fixture, "multitone_200_600_2000hz_0.5s");
  ASSERT_TRUE(tc.contains("mel_corner_values"));
  const auto& corners = tc["mel_corner_values"];

  const std::vector<float> audio =
      generateMultitone({200.0f, 600.0f, 2000.0f}, 0.5f, kMelSampleRate);
  const std::vector<float> mel = computeMelSpectrogram(audio);
  const std::size_t n_frames = mel.size() / kMelNMels;

  auto check = [](const char* name, double actual, double expected) {
    const double rel = (std::fabs(expected) > 1e-10)
                           ? std::fabs((actual - expected) / expected)
                           : std::fabs(actual - expected);
    EXPECT_LT(rel, kRelTolMelCorner) << name << ": expected " << expected
                                      << ", got " << actual;
  };

  check("top_left", static_cast<double>(mel[0 * kMelNMels + 0]),
        corners["top_left"].get<double>());
  check("top_right",
        static_cast<double>(mel[(n_frames - 1) * kMelNMels + 0]),
        corners["top_right"].get<double>());
  check("bottom_left",
        static_cast<double>(mel[0 * kMelNMels + (kMelNMels - 1)]),
        corners["bottom_left"].get<double>());
  check("bottom_right",
        static_cast<double>(
            mel[(n_frames - 1) * kMelNMels + (kMelNMels - 1)]),
        corners["bottom_right"].get<double>());
}
