// Cross-runtime ORT session contract test.
//
// Reads tests/fixtures/ort_session/contract.json (regenerated by
// scripts/regenerate_ort_session_fixture.py from
// docs/spec/ort-session-contract.toml) and asserts that the C++
// implementation in src/cpp/piper.cpp uses the same canonical values
// that the other runtimes (Python, Rust, Go, C#) match.
//
// Self-contained: re-declares the constants identically to piper.cpp so
// the test does not require linking the production library. Mirrors the
// pattern in test_short_text_contract.cpp.
//
// Production constants (must stay in sync with piper.cpp):
//   - MAX_INTRA_THREADS = 4              (piper.cpp:78)
//   - dynamic_block_base = "4"           (piper.cpp:514, AddConfigEntry)
//   - SetGraphOptimizationLevel(ORT_ENABLE_ALL) (piper.cpp:500)
//   - SetExecutionMode(ORT_SEQUENTIAL)   (piper.cpp:510)
//   - SetInterOpNumThreads(1)            (piper.cpp:511)
//   - warmup phonemeLength = 100         (piper.cpp:2967)
//   - warmup BOS = 1, EOS = 2, dummy = 8 (piper.cpp:2970-2972)
//   - warmup default runs = 2            (piper.cpp:warmupModel(...) sig in piper.h)
//   - warmup scales: noise=0.4, length=1.0, w=0.5 (piper.cpp:2973 + config defaults
//     at piper.cpp:264/272 for SynthesisConfig; v1.12.0 で全 runtime 統一)
//
// The C++ runtime does NOT implement model-cache (.opt.onnx[.ok]) nor the
// PIPER_DISABLE_WARMUP / PIPER_DISABLE_CACHE / PIPER_INTRA_THREADS env
// vars; those rows are pinned to the fixture for forward-compat drift
// detection only. See docs/spec/ort-session-contract.toml [env_vars.implementation_status].

#include <gtest/gtest.h>

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include "json.hpp"

namespace {

namespace fs = std::filesystem;
using nlohmann::json;

// ---------------------------------------------------------------------------
// Re-declare the production constants identically to src/cpp/piper.cpp so the
// tests are self-contained (no piper.cpp linkage required). If piper.cpp's
// values drift from the contract, this test must fail.
// ---------------------------------------------------------------------------

namespace cpp_constants {
// piper.cpp:78
constexpr int MAX_INTRA_THREADS = 4;
// piper.cpp:514: session.options.AddConfigEntry("session.dynamic_block_base", "4");
constexpr int DYNAMIC_BLOCK_BASE = 4;
// piper.cpp:511: session.options.SetInterOpNumThreads(1);
constexpr int INTER_OP_THREADS = 1;
// piper.cpp:2967
constexpr int WARMUP_PHONEME_LENGTH = 100;
// piper.cpp:2970-2972: BOS, dummy, EOS tokens.
constexpr int WARMUP_BOS_TOKEN = 1;
constexpr int WARMUP_EOS_TOKEN = 2;
constexpr int WARMUP_DUMMY_PHONEME = 8;
// main.cpp:294 — `piper::warmupModel(voice.session)` defaults to 2 runs
// (piper.h: void warmupModel(ModelSession &, int runs = 2);).
constexpr int WARMUP_DEFAULT_RUNS = 2;
// piper.cpp:264/272: SynthesisConfig defaults pulled into warmup at line 2973.
// v1.12.0 で全 runtime canonical 0.4/1.0/0.5 に統一済 (contract.json と整合)。
constexpr float WARMUP_NOISE_SCALE = 0.4f;
constexpr float WARMUP_LENGTH_SCALE = 1.0f;
constexpr float WARMUP_NOISE_W = 0.5f;
}  // namespace cpp_constants

// ---------------------------------------------------------------------------
// Fixture loading (mirrors test_short_text_contract.cpp / test_phoneme_timing_parity.cpp)
// ---------------------------------------------------------------------------

fs::path findFixturePath() {
  if (const char* env = std::getenv("PIPER_ORT_SESSION_FIXTURE")) {
    return fs::path(env);
  }

  const fs::path needle =
      fs::path("tests") / "fixtures" / "ort_session" / "contract.json";
  fs::path cwd = fs::current_path();
  for (int depth = 0; depth < 8; ++depth) {
    fs::path candidate = cwd / needle;
    if (fs::exists(candidate)) {
      return candidate;
    }
    if (!cwd.has_parent_path() || cwd == cwd.parent_path()) {
      break;
    }
    cwd = cwd.parent_path();
  }
  return needle;  // last resort — will fail open + give a useful error
}

json loadFixture() {
  const fs::path fixture_path = findFixturePath();
  std::ifstream stream(fixture_path);
  EXPECT_TRUE(stream.is_open())
      << "Cannot open ORT session contract fixture: " << fixture_path
      << " (cwd=" << fs::current_path()
      << "). Set PIPER_ORT_SESSION_FIXTURE if the default search path doesn't "
         "apply.";
  std::stringstream buffer;
  buffer << stream.rdbuf();
  return json::parse(buffer.str());
}

}  // namespace

// ---------------------------------------------------------------------------
// 1. Fixture sanity
// ---------------------------------------------------------------------------

TEST(OrtSessionContract, FixtureLoadsAndIsSchemaV1) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("schema_version"));
  EXPECT_EQ(fixture["schema_version"].get<int>(), 1);

  ASSERT_TRUE(fixture.contains("session"));
  ASSERT_TRUE(fixture.contains("warmup"));
  ASSERT_TRUE(fixture.contains("cache"));
  ASSERT_TRUE(fixture.contains("env_vars"));
}

// ---------------------------------------------------------------------------
// 2. Session constants
// ---------------------------------------------------------------------------

TEST(OrtSessionContract, Session_GraphOptimizationLevel) {
  const auto fixture = loadFixture();
  // piper.cpp:500-501:
  //   session.options.SetGraphOptimizationLevel(
  //       GraphOptimizationLevel::ORT_ENABLE_ALL);
  EXPECT_EQ(fixture["session"]["graph_optimization_level"].get<std::string>(),
            "ORT_ENABLE_ALL");
}

TEST(OrtSessionContract, Session_ExecutionMode) {
  const auto fixture = loadFixture();
  // piper.cpp:510:
  //   session.options.SetExecutionMode(ExecutionMode::ORT_SEQUENTIAL);
  EXPECT_EQ(fixture["session"]["execution_mode"].get<std::string>(),
            "SEQUENTIAL");
}

TEST(OrtSessionContract, Session_MaxIntraThreads) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::MAX_INTRA_THREADS,
            fixture["session"]["max_intra_threads"].get<int>());
}

TEST(OrtSessionContract, Session_InterOpThreads) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::INTER_OP_THREADS,
            fixture["session"]["inter_op_threads"].get<int>());
}

TEST(OrtSessionContract, Session_DynamicBlockBase) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::DYNAMIC_BLOCK_BASE,
            fixture["session"]["dynamic_block_base"].get<int>());
}

TEST(OrtSessionContract, Session_EnableCpuMemArena_FixtureValue) {
  const auto fixture = loadFixture();
  // piper.cpp:503-507 documents that CPU memory arena and memory pattern are
  // left at the ORT defaults (i.e. enabled). We don't call DisableCpuMemArena()
  // anywhere in piper.cpp, so contract value `true` is preserved.
  EXPECT_TRUE(fixture["session"]["enable_cpu_mem_arena"].get<bool>());
}

TEST(OrtSessionContract, Session_EnableMemoryPattern_FixtureValue) {
  const auto fixture = loadFixture();
  // piper.cpp:503-507: ORT default is enabled, no DisableMemPattern() call.
  EXPECT_TRUE(fixture["session"]["enable_memory_pattern"].get<bool>());
}

// ---------------------------------------------------------------------------
// 3. Warmup constants
// ---------------------------------------------------------------------------

TEST(OrtSessionContract, Warmup_PhonemeLength) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::WARMUP_PHONEME_LENGTH,
            fixture["warmup"]["phoneme_length"].get<int>());
}

TEST(OrtSessionContract, Warmup_DefaultRuns) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::WARMUP_DEFAULT_RUNS,
            fixture["warmup"]["default_runs"].get<int>());
}

TEST(OrtSessionContract, Warmup_BosToken) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::WARMUP_BOS_TOKEN,
            fixture["warmup"]["bos_token"].get<int>());
}

TEST(OrtSessionContract, Warmup_EosToken) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::WARMUP_EOS_TOKEN,
            fixture["warmup"]["eos_token"].get<int>());
}

TEST(OrtSessionContract, Warmup_DummyPhoneme) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::WARMUP_DUMMY_PHONEME,
            fixture["warmup"]["dummy_phoneme"].get<int>());
}

TEST(OrtSessionContract, Warmup_NoiseScale) {
  const auto fixture = loadFixture();
  EXPECT_FLOAT_EQ(cpp_constants::WARMUP_NOISE_SCALE,
                  fixture["warmup"]["noise_scale"].get<float>());
}

TEST(OrtSessionContract, Warmup_LengthScale) {
  const auto fixture = loadFixture();
  EXPECT_FLOAT_EQ(cpp_constants::WARMUP_LENGTH_SCALE,
                  fixture["warmup"]["length_scale"].get<float>());
}

TEST(OrtSessionContract, Warmup_NoiseW) {
  const auto fixture = loadFixture();
  EXPECT_FLOAT_EQ(cpp_constants::WARMUP_NOISE_W,
                  fixture["warmup"]["noise_w"].get<float>());
}

// ---------------------------------------------------------------------------
// 4. Cache constants — NOT implemented in C++.
//
// piper.cpp does not read or write `.opt.onnx` / `.opt.onnx.ok` artifacts;
// the optimised-model cache lives in the Python runtime only (see
// src/python/piper_train/ort_utils.py). We still pin the fixture values
// so the C++ runtime catches any contract-side rename and consciously
// decides whether to implement caching.
// ---------------------------------------------------------------------------

TEST(OrtSessionContract, Cache_OptimizedExtension_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["cache"]["optimized_extension"].get<std::string>(),
            "opt.onnx");
}

TEST(OrtSessionContract, Cache_SentinelExtension_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["cache"]["sentinel_extension"].get<std::string>(),
            "opt.onnx.ok");
}

TEST(OrtSessionContract, Cache_SentinelContent_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["cache"]["sentinel_content"].get<std::string>(), "ok");
}

// ---------------------------------------------------------------------------
// 5. Env vars — NOT implemented in C++.
//
// The C++ runtime gates warmup via `--no-warmup` (main.cpp:935) only; it
// does not honour PIPER_DISABLE_WARMUP / PIPER_DISABLE_CACHE /
// PIPER_INTRA_THREADS. These cases pin the contract values so any rename
// trips the test before drift hits a multi-runtime release.
// ---------------------------------------------------------------------------

TEST(OrtSessionContract, EnvVars_DisableWarmup_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["env_vars"]["disable_warmup"].get<std::string>(),
            "PIPER_DISABLE_WARMUP");
}

TEST(OrtSessionContract, EnvVars_DisableCache_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["env_vars"]["disable_cache"].get<std::string>(),
            "PIPER_DISABLE_CACHE");
}

TEST(OrtSessionContract, EnvVars_IntraThreads_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["env_vars"]["intra_threads"].get<std::string>(),
            "PIPER_INTRA_THREADS");
}
