// Cross-runtime short-text mitigation contract test.
//
// Reads tests/fixtures/short_text/contract.json (regenerated by
// scripts/regenerate_short_text_fixture.py from
// docs/spec/short-text-contract.toml) and asserts that the C++
// implementation in src/cpp/piper.cpp uses the same canonical values
// that the other runtimes (Python, Rust, Go, C#, WASM/JS) match.
//
// Self-contained: re-declares the constants identically to piper.cpp so
// the test does not require linking the production library. The existing
// test_short_text_mitigation.cpp uses the same pattern.
//
// Strategy C (SSML <break> auto-injection) is not implemented in C++,
// so its constants (short_text_chars, silence_pad_ms, skip_if_ssml) are
// only checked against the fixture for forward-compat (drift detection),
// not against any C++ const.

#include <gtest/gtest.h>

#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

#include "json.hpp"

namespace {

namespace fs = std::filesystem;
using nlohmann::json;

// ---------------------------------------------------------------------------
// Re-declare the constants identically to src/cpp/piper.cpp:84-97 so the
// tests are self-contained (no piper.cpp linkage required). If piper.cpp's
// values drift from the contract, this test must fail.
// ---------------------------------------------------------------------------

namespace cpp_constants {
constexpr int MIN_PHONEME_IDS = 15;
constexpr int MIN_BODY_FOR_STRATEGY_A = 3;
constexpr float TRIM_THRESHOLD_RMS = 0.01f;
constexpr int TRIM_MIN_SAMPLES = 2205;  // 22050 Hz * 0.1 s
constexpr int TRIM_WINDOW_SIZE = 256;
constexpr int TRIM_SAMPLE_RATE = 22050;
// Default pad token used by padPhonemeIds in piper.cpp:712
//   bool padPhonemeIds(..., PhonemeId padId = 0, ...)
constexpr int PAD_TOKEN_ID = 0;
// Strategy B (dynamic scales) hard-coded floors at piper.cpp:1149-1150 and
// 1349-1350:
//   effectiveNoiseScale *= std::max(0.5f, ratio);
//   effectiveNoiseW     *= std::max(0.4f, ratio);
constexpr float NOISE_SCALE_MIN_RATIO = 0.5f;
constexpr float NOISE_W_MIN_RATIO = 0.4f;
}  // namespace cpp_constants

// ---------------------------------------------------------------------------
// Fixture loading (mirrors test_phoneme_timing_parity.cpp)
// ---------------------------------------------------------------------------

fs::path findFixturePath() {
  if (const char* env = std::getenv("PIPER_SHORT_TEXT_FIXTURE")) {
    return fs::path(env);
  }

  const fs::path needle =
      fs::path("tests") / "fixtures" / "short_text" / "contract.json";
  fs::path cwd = fs::current_path();
  for (int depth = 0; depth < 8; ++depth) {
    fs::path candidate = cwd / needle;
    if (fs::exists(candidate)) {
      return candidate;
    }
    if (!cwd.has_parent_path() || cwd == cwd.parent_path()) {
      break;
    }
    cwd = cwd.parent_path();
  }
  return needle;  // last resort — will fail open + give a useful error
}

json loadFixture() {
  const fs::path fixture_path = findFixturePath();
  std::ifstream stream(fixture_path);
  EXPECT_TRUE(stream.is_open())
      << "Cannot open short-text contract fixture: " << fixture_path
      << " (cwd=" << fs::current_path()
      << "). Set PIPER_SHORT_TEXT_FIXTURE if the default search path doesn't "
         "apply.";
  std::stringstream buffer;
  buffer << stream.rdbuf();
  return json::parse(buffer.str());
}

}  // namespace

// ---------------------------------------------------------------------------
// 1. Fixture sanity
// ---------------------------------------------------------------------------

TEST(ShortTextContract, FixtureLoadsAndIsSchemaV1) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("schema_version"));
  EXPECT_EQ(fixture["schema_version"].get<int>(), 1);

  ASSERT_TRUE(fixture.contains("padding"));
  ASSERT_TRUE(fixture.contains("trim"));
  ASSERT_TRUE(fixture.contains("scales"));
  ASSERT_TRUE(fixture.contains("ssml_injection"));
}

// ---------------------------------------------------------------------------
// 2. Padding constants (Strategy A)
// ---------------------------------------------------------------------------

TEST(ShortTextContract, Padding_MinPhonemeIds) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::MIN_PHONEME_IDS,
            fixture["padding"]["min_phoneme_ids"].get<int>());
}

TEST(ShortTextContract, Padding_MinBodyForStrategyA) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::MIN_BODY_FOR_STRATEGY_A,
            fixture["padding"]["min_body_for_strategy_a"].get<int>());
}

TEST(ShortTextContract, Padding_PauseTokenId) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::PAD_TOKEN_ID,
            fixture["padding"]["pause_token_id"].get<int>());
}

TEST(ShortTextContract, Padding_SplitIsFrontBackEven) {
  const auto fixture = loadFixture();
  // Spec [padding].split = "front_back_even":
  //   front = needed / 2; back = needed - front;
  // matches piper.cpp:721-722 verbatim.
  EXPECT_EQ(fixture["padding"]["split"].get<std::string>(), "front_back_even");

  // Behavioural retention: piper.cpp uses needed/2 for front, leaving the
  // extra token in `back` when `needed` is odd (`needed - front`).
  // Spec mirror: deficit=9 (odd) -> front=4, back=5.
  const int needed = 9;
  const int front = needed / 2;
  const int back = needed - front;
  EXPECT_EQ(front, 4);
  EXPECT_EQ(back, 5);
}

TEST(ShortTextContract, Padding_ProsodyFill) {
  const auto fixture = loadFixture();
  // C++ piper.cpp does not currently propagate prosody features through
  // padding (no prosody-fill code path), but the contract value still
  // pins what *would* be filled if prosody were ever wired in.
  EXPECT_EQ(fixture["padding"]["prosody_fill"].get<int>(), 0);
}

// ---------------------------------------------------------------------------
// 3. Trim constants (Strategy A post-processing)
// ---------------------------------------------------------------------------

TEST(ShortTextContract, Trim_ThresholdRms) {
  const auto fixture = loadFixture();
  EXPECT_FLOAT_EQ(cpp_constants::TRIM_THRESHOLD_RMS,
                  fixture["trim"]["threshold_rms"].get<float>());
}

TEST(ShortTextContract, Trim_MinSamples) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::TRIM_MIN_SAMPLES,
            fixture["trim"]["min_samples"].get<int>());
}

TEST(ShortTextContract, Trim_WindowSize) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::TRIM_WINDOW_SIZE,
            fixture["trim"]["window_size"].get<int>());
}

TEST(ShortTextContract, Trim_SampleRate) {
  const auto fixture = loadFixture();
  EXPECT_EQ(cpp_constants::TRIM_SAMPLE_RATE,
            fixture["trim"]["sample_rate"].get<int>());
}

// ---------------------------------------------------------------------------
// 4. Strategy B scales (dynamic noise floors)
// ---------------------------------------------------------------------------

TEST(ShortTextContract, Scales_NoiseScaleMinRatio) {
  const auto fixture = loadFixture();
  EXPECT_FLOAT_EQ(cpp_constants::NOISE_SCALE_MIN_RATIO,
                  fixture["scales"]["noise_scale_min_ratio"].get<float>());
}

TEST(ShortTextContract, Scales_NoiseWMinRatio) {
  const auto fixture = loadFixture();
  EXPECT_FLOAT_EQ(cpp_constants::NOISE_W_MIN_RATIO,
                  fixture["scales"]["noise_w_min_ratio"].get<float>());
}

// ---------------------------------------------------------------------------
// 5. Strategy C (SSML <break>) — NOT implemented in C++.
//
// These cases pin the contract values for forward-compat: if the spec
// tightens these numbers, the C++ runtime must consciously decide to
// either implement Strategy C or update the test. See WASM/JS runtime
// test (test-short-text-contract.js) for the same todo treatment.
// ---------------------------------------------------------------------------

TEST(ShortTextContract, SsmlInjection_ShortTextChars_FixtureValue) {
  const auto fixture = loadFixture();
  // Strategy C threshold below which <break> is auto-injected.
  // C++ has no equivalent constant (Strategy C unimplemented); we only
  // assert the fixture still carries the expected number so per-runtime
  // implementations stay aligned when C++ catches up.
  EXPECT_EQ(fixture["ssml_injection"]["short_text_chars"].get<int>(), 10);
}

TEST(ShortTextContract, SsmlInjection_SilencePadMs_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_EQ(fixture["ssml_injection"]["silence_pad_ms"].get<int>(), 300);
}

TEST(ShortTextContract, SsmlInjection_SkipIfSsml_FixtureValue) {
  const auto fixture = loadFixture();
  EXPECT_TRUE(fixture["ssml_injection"]["skip_if_ssml"].get<bool>());
}
