// Cross-runtime phoneme timing parity test.
//
// Loads tests/fixtures/phoneme_timing/golden_matrix.json (generated by
// scripts/regenerate_timing_fixture.py from src/python_run/piper/timing.py)
// and asserts that the spec-defined cursor-walk algorithm in C++ produces
// the same output as the Python canonical implementation, byte-for-byte.
//
// The spec (docs/spec/phoneme-timing-contract.toml) defines:
//
//   frame_time_ms = (hop_length / sample_rate) * 1000
//   cursor_ms = 0.0
//   for each (duration_frames, phoneme_token):
//       duration_ms = max(duration_frames, 0.0) * frame_time_ms
//       start_ms = cursor_ms
//       end_ms   = cursor_ms + duration_ms
//       yield {phoneme, start_ms, end_ms, duration_ms}
//       cursor_ms = end_ms
//
// Note: the production helper piper.cpp:extractTimingsFromDurations operates
// on integer PhonemeIds (skipping PAD/BOS/EOS) and reports times in seconds.
// To stay self-contained (no onnxruntime/espeak link), this test re-implements
// the spec algorithm against the fixture's string tokens and ms timestamps,
// catching drift between the spec, the Python canonical, and the C++ math.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "json.hpp"

namespace {

namespace fs = std::filesystem;
using nlohmann::json;

// Floating-point tolerance for parity comparison.
// Python computes via float64; our cursor-walk is also float64. A handful of
// ULPs is reasonable; 1e-6 ms is comfortably tighter than any meaningful drift.
constexpr double kAbsTolMs = 1e-6;

struct ComputedEntry {
  std::string phoneme;
  double start_ms;
  double end_ms;
  double duration_ms;
};

struct ComputedResult {
  std::vector<ComputedEntry> phonemes;
  double total_duration_ms;
  int sample_rate;
};

// Spec [calculation] cursor-walk applied verbatim.
ComputedResult computeFromSpec(const std::vector<double>& durations,
                               const std::vector<std::string>& phoneme_tokens,
                               int sample_rate, int hop_length) {
  ComputedResult out;
  out.sample_rate = sample_rate;
  const double frame_time_ms =
      (static_cast<double>(hop_length) / static_cast<double>(sample_rate)) *
      1000.0;

  double cursor_ms = 0.0;
  const size_t n = std::min(durations.size(), phoneme_tokens.size());
  out.phonemes.reserve(n);
  for (size_t i = 0; i < n; ++i) {
    double dur_frames = durations[i];
    if (dur_frames < 0.0) {
      dur_frames = 0.0;  // spec [calculation.negative_handling]
    }
    const double duration_ms = dur_frames * frame_time_ms;
    ComputedEntry e{phoneme_tokens[i], cursor_ms, cursor_ms + duration_ms,
                    duration_ms};
    out.phonemes.push_back(std::move(e));
    cursor_ms += duration_ms;
  }
  out.total_duration_ms = cursor_ms;
  return out;
}

// ---------------------------------------------------------------------------
// Fixture loading
// ---------------------------------------------------------------------------

fs::path findFixturePath() {
  // Allow CI / build systems to override.
  if (const char* env = std::getenv("PIPER_TIMING_FIXTURE")) {
    return fs::path(env);
  }

  // Walk upwards from the current working directory looking for the fixture.
  // The CMake test sets WORKING_DIRECTORY to CMAKE_SOURCE_DIR (repo root) for
  // the foreach loop above, but our standalone test runs without that — so be
  // robust to either.
  const fs::path needle = fs::path("tests") / "fixtures" / "phoneme_timing" /
                          "golden_matrix.json";
  fs::path cwd = fs::current_path();
  for (int depth = 0; depth < 8; ++depth) {
    fs::path candidate = cwd / needle;
    if (fs::exists(candidate)) {
      return candidate;
    }
    if (!cwd.has_parent_path() || cwd == cwd.parent_path()) {
      break;
    }
    cwd = cwd.parent_path();
  }
  return needle;  // last resort — will fail open + give a useful error
}

json loadFixture() {
  const fs::path fixture_path = findFixturePath();
  std::ifstream stream(fixture_path);
  EXPECT_TRUE(stream.is_open())
      << "Cannot open phoneme timing fixture: " << fixture_path
      << " (cwd=" << fs::current_path() << "). Set PIPER_TIMING_FIXTURE if the "
                                           "default search path doesn't apply.";
  std::stringstream buffer;
  buffer << stream.rdbuf();
  return json::parse(buffer.str());
}

}  // namespace

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

// Smoke test: fixture is loadable and at the expected schema version.
TEST(PhonemeTimingParity, FixtureLoadsAndIsSchemaV1) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("schema_version"));
  EXPECT_EQ(fixture["schema_version"].get<int>(), 1);
  ASSERT_TRUE(fixture.contains("cases"));
  EXPECT_GT(fixture["cases"].size(), 0u);
}

// One assertion per case × per phoneme — produces a clear failure message
// when a single case drifts.
TEST(PhonemeTimingParity, AllCasesMatchPythonCanonical) {
  const auto fixture = loadFixture();
  ASSERT_TRUE(fixture.contains("cases"));

  for (const auto& test_case : fixture["cases"]) {
    const std::string name = test_case.value("name", "<unnamed>");
    SCOPED_TRACE("case=" + name);

    const auto& inputs = test_case["inputs"];
    std::vector<double> durations;
    for (const auto& d : inputs["durations"]) {
      durations.push_back(d.get<double>());
    }
    std::vector<std::string> phoneme_tokens;
    for (const auto& t : inputs["phoneme_tokens"]) {
      phoneme_tokens.push_back(t.get<std::string>());
    }
    const int sample_rate = inputs["sample_rate"].get<int>();
    const int hop_length = inputs["hop_length"].get<int>();

    const ComputedResult got =
        computeFromSpec(durations, phoneme_tokens, sample_rate, hop_length);

    const auto& expected = test_case["expected"];
    EXPECT_EQ(got.sample_rate, expected["sample_rate"].get<int>());

    EXPECT_NEAR(got.total_duration_ms,
                expected["total_duration_ms"].get<double>(), kAbsTolMs)
        << "total_duration_ms mismatch in case " << name;

    const auto& expected_phonemes = expected["phonemes"];
    ASSERT_EQ(got.phonemes.size(), expected_phonemes.size())
        << "phoneme count mismatch in case " << name;

    for (size_t i = 0; i < got.phonemes.size(); ++i) {
      SCOPED_TRACE("phoneme[" + std::to_string(i) + "]");
      EXPECT_EQ(got.phonemes[i].phoneme,
                expected_phonemes[i]["phoneme"].get<std::string>());
      EXPECT_NEAR(got.phonemes[i].start_ms,
                  expected_phonemes[i]["start_ms"].get<double>(), kAbsTolMs);
      EXPECT_NEAR(got.phonemes[i].end_ms,
                  expected_phonemes[i]["end_ms"].get<double>(), kAbsTolMs);
      EXPECT_NEAR(got.phonemes[i].duration_ms,
                  expected_phonemes[i]["duration_ms"].get<double>(), kAbsTolMs);
    }
  }
}

// Spec [calculation.negative_handling]: negative durations are clamped to 0.
TEST(PhonemeTimingParity, NegativeDurationsClampedExplicitly) {
  const std::vector<double> durations = {3.0, -2.0, 5.0};
  const std::vector<std::string> tokens = {"a", "b", "c"};
  const int sample_rate = 22050;
  const int hop_length = 256;

  const ComputedResult got =
      computeFromSpec(durations, tokens, sample_rate, hop_length);

  ASSERT_EQ(got.phonemes.size(), 3u);
  EXPECT_EQ(got.phonemes[1].phoneme, "b");
  EXPECT_DOUBLE_EQ(got.phonemes[1].duration_ms, 0.0);
  // Cursor must not regress: 'c' starts where 'b' ended.
  EXPECT_DOUBLE_EQ(got.phonemes[2].start_ms, got.phonemes[1].end_ms);
}

// Spec: empty input → empty result, total_duration_ms = 0.
TEST(PhonemeTimingParity, EmptyInputProducesEmptyResult) {
  const ComputedResult got = computeFromSpec({}, {}, 22050, 256);
  EXPECT_TRUE(got.phonemes.empty());
  EXPECT_DOUBLE_EQ(got.total_duration_ms, 0.0);
  EXPECT_EQ(got.sample_rate, 22050);
}
