#!/usr/bin/env python3
"""Generate Python golden phonemes for cross-runtime parity (Issue #388).

Reads ``tests/fixtures/g2p/phoneme_test_cases.json`` and produces
``tests/fixtures/g2p/phoneme_test_cases_golden.json`` by running each
non-Japanese case through ``piper_plus_g2p.MultilingualPhonemizer``.

The Kotlin Android AAR's instrumented test then asserts byte-for-byte
equality against this golden file. JA cases are intentionally skipped
because they require the OpenJTalk dictionary (~102 MB) which is not
bundled in the test APK.

Run with::

    uv run --with-editable src/python/g2p \\
        python tools/generate_g2p_golden.py
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def _load_phonemizer():
    from piper_plus_g2p import MultilingualPhonemizer  # type: ignore

    # Eight built-in languages. Order matters only in that the first listed
    # language becomes the fallback target when ``default_latin_language``
    # is not present in the list. We keep the trained 6lang ID order
    # (ja, en, zh, es, fr, pt) plus ko/sv to mirror the C API.
    return MultilingualPhonemizer(
        languages=["en", "es", "fr", "ja", "ko", "pt", "sv", "zh"],
        default_latin_language="en",
    )


def _phonemize_one(phonemizer, text: str) -> str:
    tokens = phonemizer.phonemize(text)
    return " ".join(tokens)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        default="tests/fixtures/g2p/phoneme_test_cases.json",
        help="Input fixture path",
    )
    parser.add_argument(
        "--output",
        default="tests/fixtures/g2p/phoneme_test_cases_golden.json",
        help="Output golden fixture path",
    )
    parser.add_argument(
        "--include-ja",
        action="store_true",
        help="Also pre-compute JA cases (requires OpenJTalk dictionary).",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    in_path = (repo_root / args.input).resolve()
    out_path = (repo_root / args.output).resolve()

    if not in_path.exists():
        print(f"Input fixture not found: {in_path}", file=sys.stderr)
        return 1

    fixture = json.loads(in_path.read_text(encoding="utf-8"))
    cases: list[dict[str, Any]] = fixture.get("test_cases", [])

    phonemizer = _load_phonemizer()

    golden_cases: list[dict[str, Any]] = []
    skipped = 0
    for case in cases:
        lang: str = case["language"]
        if lang == "ja" and not args.include_ja:
            skipped += 1
            continue
        text: str = case["input"]
        try:
            golden_str = _phonemize_one(phonemizer, text)
        except Exception as exc:  # noqa: BLE001
            print(
                f"WARN: phonemize failed for [{lang}] '{text}': {exc}",
                file=sys.stderr,
            )
            continue
        golden_cases.append(
            {
                "language": lang,
                "input": text,
                "description": case.get("description", ""),
                "expected_phonemes": golden_str,
                "expected_token_count": len(golden_str.split(" ")) if golden_str else 0,
            }
        )

    out = {
        "version": 1,
        "source_fixture": str(in_path.relative_to(repo_root)).replace("\\", "/"),
        "generator": "tools/generate_g2p_golden.py",
        "description": (
            "Python pre-computed golden phonemes for byte-for-byte cross-runtime "
            "parity tests. Generated by piper_plus_g2p.MultilingualPhonemizer. "
            "Kotlin / Rust / Go / WASM / C# / C++ runtimes assert string equality "
            "against `expected_phonemes`."
        ),
        "skipped_ja_cases": skipped,
        "test_cases": golden_cases,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(out, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(
        f"Wrote {len(golden_cases)} golden cases (skipped {skipped} JA) to {out_path}",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
