# cmake/EmbedJson.cmake
# Driver invoked via `cmake -P` from `piper_embed_json_as_header()`.
#
# Required script-mode variables (passed via -D):
#   INPUT_JSON     : absolute path to the source JSON
#   OUTPUT_HEADER  : absolute path to the generated C header
#   VAR_NAME       : C identifier for the generated array
#
# CRLF in the working tree is folded to LF before hashing so the embedded
# payload is byte-for-byte identical across Windows / Linux / macOS check-outs.
# (Review note Cpp-C1.)

if(NOT INPUT_JSON)
  message(FATAL_ERROR "EmbedJson.cmake: INPUT_JSON not set")
endif()
if(NOT OUTPUT_HEADER)
  message(FATAL_ERROR "EmbedJson.cmake: OUTPUT_HEADER not set")
endif()
if(NOT VAR_NAME)
  message(FATAL_ERROR "EmbedJson.cmake: VAR_NAME not set")
endif()
if(NOT EXISTS "${INPUT_JSON}")
  message(FATAL_ERROR "EmbedJson.cmake: input file not found: ${INPUT_JSON}")
endif()

# Read as raw bytes (HEX) and strip CR (0x0d) bytes that could come from a
# Windows checkout. Operating on the HEX stream avoids depending on either
# `file(READ)` text-mode semantics or `file(WRITE)` line-ending behavior, both
# of which differ across CMake versions and host platforms.
file(READ "${INPUT_JSON}" _hex_content HEX)
file(SIZE "${INPUT_JSON}" _raw_byte_count)

if(_raw_byte_count EQUAL 0)
  message(FATAL_ERROR "EmbedJson.cmake: input file is empty: ${INPUT_JSON}")
endif()

# Drop every CR byte (0x0d). This collapses CRLF -> LF and the rare bare CR
# (old-Mac line endings) to LF. JSON is whitespace-insensitive so the parser
# is unaffected, and downstream consumers see the same bytes as a Linux
# checkout would have produced.
string(REPLACE "0d" "" _hex_content "${_hex_content}")

# `0x..,0x..,...` (no trailing comma).
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _c_array "${_hex_content}")
string(REGEX REPLACE ",$" "" _c_array "${_c_array}")

# Normalized byte count = HEX-string length / 2 (after CR removal).
string(LENGTH "${_hex_content}" _hex_len)
math(EXPR _byte_count "${_hex_len} / 2")

file(WRITE "${OUTPUT_HEADER}"
  "// Auto-generated by piper_embed_json_as_header (CMake). DO NOT EDIT.\n"
  "// Source: ${INPUT_JSON}\n"
  "// Raw bytes: ${_raw_byte_count}; LF-normalized bytes: ${_byte_count}\n"
  "#pragma once\n"
  "#include <cstddef>\n"
  "static const unsigned char ${VAR_NAME}[] = { ${_c_array} };\n"
  "static const std::size_t ${VAR_NAME}_len = sizeof(${VAR_NAME});\n"
)
