# Makefile fragment for building open_jtalk_phonemizer

bin_PROGRAMS += open_jtalk_phonemizer

open_jtalk_phonemizer_SOURCES = open_jtalk_phonemizer.c
open_jtalk_phonemizer_CFLAGS = @CFLAGS@
open_jtalk_phonemizer_LDADD = ../text2mecab/libtext2mecab.la \
	../mecab2njd/libmecab2njd.la \
	../njd_set_pronunciation/libnjd_set_pronunciation.la \
	../njd_set_digit/libnjd_set_digit.la \
	../njd_set_accent_phrase/libnjd_set_accent_phrase.la \
	../njd_set_accent_type/libnjd_set_accent_type.la \
	../njd_set_unvoiced_vowel/libnjd_set_unvoiced_vowel.la \
	../njd_set_long_vowel/libnjd_set_long_vowel.la \
	../njd2jpcommon/libnjd2jpcommon.la \
	../jpcommon/libjpcommon.la \
	../mecab/src/libmecab.la \
	../njd/libnjd.la \
	$(HTS_ENGINE_LIB)