"""Golden phoneme drift tests for ES / PT / FR / SV.

Loads ``tests/fixtures/g2p/{es,pt,fr,sv}_golden.json`` and asserts that
each ``expected_phonemes`` list matches the current phonemizer output
exactly. The fixtures were generated by

    scripts/regenerate_g2p_golden_fixtures.py

and pin the *implementation's current behaviour* (not a linguistic
ideal). Any drift in a single rule -- spirantization, ñ → ɲ, ille → ij,
retroflex assimilation, palatalisation, etc. -- will fail this test
and prevent silent regressions.

If a failure is intentional (e.g. a rule was updated on purpose), run
``python scripts/regenerate_g2p_golden_fixtures.py`` to regenerate.

Reference fixture: ``tests/fixtures/g2p/zh_en_loanword_matrix.json``.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from piper_plus_g2p import get_phonemizer

# Repo root: tests/test_golden_fixtures.py -> g2p/ -> python/ -> src/ -> repo
_REPO_ROOT = Path(__file__).resolve().parents[4]
_FIXTURE_DIR = _REPO_ROOT / "tests" / "fixtures" / "g2p"

LANGUAGES = ("es", "pt", "fr", "sv")


def _load_fixture(language: str) -> dict:
    path = _FIXTURE_DIR / f"{language}_golden.json"
    if not path.exists():
        pytest.fail(
            f"Golden fixture missing: {path}. "
            "Regenerate via scripts/regenerate_g2p_golden_fixtures.py."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def _iter_cases(language: str):
    fixture = _load_fixture(language)
    for case in fixture["cases"]:
        yield pytest.param(
            language,
            case["text"],
            list(case["expected_phonemes"]),
            case.get("notes", ""),
            id=f"{language}::{case['text']}",
        )


# ---------------------------------------------------------------------------
# Per-language fixture sanity (schema invariants)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("language", LANGUAGES)
def test_fixture_schema(language: str) -> None:
    """Each fixture must be schema-version 1 and non-empty."""
    fixture = _load_fixture(language)
    assert fixture["schema_version"] == 1, (
        f"{language}_golden.json: unexpected schema_version {fixture['schema_version']}"
    )
    assert fixture["language"] == language, (
        f"{language}_golden.json: 'language' field is "
        f"{fixture['language']!r}, expected {language!r}"
    )
    assert isinstance(fixture["cases"], list)
    # Drift gate: ensure we don't silently lose coverage.
    assert len(fixture["cases"]) >= 50, (
        f"{language}_golden.json has only {len(fixture['cases'])} cases; "
        "the matrix must keep at least 50 to retain drift coverage."
    )


@pytest.mark.parametrize("language", LANGUAGES)
def test_fixture_unique_inputs(language: str) -> None:
    """Each fixture's ``text`` values must be unique to avoid silent dedup."""
    fixture = _load_fixture(language)
    texts = [case["text"] for case in fixture["cases"]]
    assert len(texts) == len(set(texts)), (
        f"{language}_golden.json contains duplicate inputs: "
        f"{[t for t in texts if texts.count(t) > 1]}"
    )


# ---------------------------------------------------------------------------
# Drift detection: phonemizer output must match the fixture exactly
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("language", "text", "expected", "notes"),
    [param for lang in LANGUAGES for param in _iter_cases(lang)],
)
def test_golden_phonemes(
    language: str,
    text: str,
    expected: list[str],
    notes: str,
) -> None:
    """Phonemizer output must match the pinned fixture for every case."""
    phonemizer = get_phonemizer(language)
    actual = phonemizer.phonemize(text)
    assert list(actual) == expected, (
        f"[{language}] drift detected for {text!r} ({notes}):\n"
        f"  expected: {expected}\n"
        f"  actual:   {list(actual)}\n"
        "If the drift is intentional, regenerate via "
        "`python scripts/regenerate_g2p_golden_fixtures.py`."
    )


# ---------------------------------------------------------------------------
# Lightweight per-language smoke (covers the parametrize ID being correct
# and ensures the per-language matrix exercises the rules listed in the
# CLAUDE.md "必須カバー" sections without enforcing exact phonemes here --
# exactness is owned by ``test_golden_phonemes``).
# ---------------------------------------------------------------------------


_REQUIRED_INPUTS: dict[str, set[str]] = {
    # Each set lists representative inputs that *must* exist in the
    # fixture; these correspond to the CLAUDE.md "必須カバー" categories.
    "es": {
        "hola",
        "gracias",
        "perro",
        "lluvia",
        "mañana",
        "chico",
        "queso",
        "guitarra",
        "canción",
        "café",
        "fácil",
        "hierro",
        "transporte",
        "obstáculo",
        "de",
        "la",
    },
    "pt": {
        "irmã",
        "entender",
        "sim",
        "limão",
        "manhã",
        "melhor",
        "chão",
        "cidade",
        "novo",
        "brasil",
        "mesa",
        "tia",
        "dia",
    },
    "fr": {
        "les amis",
        "mes amis",
        "un ami",
        "très important",
        "l'eau",
        "j'ai",
        "c'est",
        "n'a",
        "qu'est",
        "bon",
        "vin",
        "fin",
        "petit",
        "grand",
        "parle",
        "famille",
        "soleil",
        "oreille",
        "été",
        "où",
        "à",
        "ça",
        "hier",
        "fier",
        "cher",
    },
    "sv": {
        "sjö",
        "skön",
        "station",
        "tjugo",
        "kjol",
        "kort",
        "hjärta",
        "mars",
        "kär",
        "kö",
        "katt",
        "gärna",
        "gata",
        "matt",
        "mat",
        "nation",
        "pension",
    },
}


@pytest.mark.parametrize("language", LANGUAGES)
def test_required_coverage(language: str) -> None:
    """Each fixture must include every CLAUDE.md "必須カバー" anchor."""
    fixture = _load_fixture(language)
    inputs = {case["text"] for case in fixture["cases"]}
    missing = _REQUIRED_INPUTS[language] - inputs
    assert not missing, (
        f"{language}_golden.json is missing required coverage anchors: "
        f"{sorted(missing)}. Update the matrix in "
        "scripts/regenerate_g2p_golden_fixtures.py and regenerate."
    )
